components/helper/MarkdownContent.tsx, components/helper/MarkdownGrid.tsx, pages/[solution]/[product].tsx, pages/[solution]/index.tsx, pages/community.tsx, pages/discover.tsx, pages/docs.tsx, pages/help.tsx, pages/index.tsx, pages/integrations/xm-cdp/index.tsx, pages/learn.tsx
Opening against parent branch for now, will change to main once parent has been merged in.
Added 2 markdown layout components that take an array of partials as args and display them appropriately.
`MarkdownContent` is intended for the body content of child pages
`MarkdownGrid` is intended for those card list ones that we see on parent pages
=> Added markdown layout components.

pages/integrations/[integration].tsx, scripts/static-paths.ts
Changed the integrations page to now be dynamically generated.
@bhgeorge, I followed the same pattern you created for Solution & Product dynamic pages, so it would be good to get your eyes across this to ensure it makes sense 😁
=> Updated integrations page to be dynamically generated

components/integrations/stackexchange/StackExchange.api.ts
A bit ugly. But this should prevent us from breaking the 30 per second limit.
My local tests have this returning an average of 45ms between requests. Anything above 33.33 should be safe.
=> Added simple delay to stackexchange requests to prevent rate limiting.

components/site/Nav/Nav.tsx, components/site/Nav/NavMenu.tsx, data/data-navigation.ts
This branch "disables" search in the navigation. Only two files are affected, `Nav.tsx` and `NavMenu.tsx`. Each file has the same instructions commented at the top, and each change location is marked with the `@TODO: Adding search back`. 
Pretty simply all around, but it will take all of 30 seconds to "enable" search (from a UI perspective :P).
Re-orderd nav items.
Closes #88 and #97.
=> Removed search from navigation per #88, reordered top level nav items per #97

data/markdown/pages/solution/commerce/index.md, data/markdown/pages/solution/devops/index.md, data/markdown/pages/solution/digital-asset-management/index.md, data/markdown/pages/solution/marketing-automation/index.md, data/markdown/pages/solution/personalization-testing/index.md
Some of the top level Solution pages still had emoji's in the title, whereas some had been tidied to remove them.
This PR removes the remaining ones to bring them all inline.
=> Removed emjois from page header meta where it still existed

.github/workflows/deploy.yml, README.md
Added logic to disable the Github Action `deploy` step in certain scenarios. 
Breakdown of the logic is.....
`github.repository_owner == 'Sitecore'` This step will only fire for repo's within the Sitecore Org, meaning that Forks where actions have been enabled won't execute this step. Secrets aren't passed to Forks so this isn't an issue from our side but will stop Forks from having a heap of failed actions executing on them.
`((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))` The PR repo and target must be the same (i.e. disable this step for external PR's), or it must be a push (i.e. we still want this step to fire for pushes on our branches to be able to test before opening PR).
=> Disable deploy on forks

data/markdown/partials/solution/devops/containers.md
Should be 'Sitecore' not 'Sitecores'
Fixes #165
=> Removing the extra 's' on the containers page

data/markdown/partials/learn/getting-started/platform-dxp-development-frameworks.md, data/markdown/partials/solution/content-management/sxa.md
The new playlist setting will make sure users can navigate to the next episode in the tutorial series.
Fixes #170
=> Updating YouTube links to SXA tutorial series to specify playlist

components/layout/InPageNav/InPageNav.tsx, components/site/Nav/Nav.tsx, components/site/Nav/NavLink.tsx, components/site/Nav/NavMenu.tsx, data/data-navigation.ts
When the user is on a page under one of the main nav sections, that section will now have the highlighted state.
Extra context to the user to understand what they're reading
Manual confirmation in local environment
- No pages highlighted on home
- Pages highlighted for a simple URL `/community`
- Solution category highlighted only when on the Solutions parent page
- Product category highlighted only when on a Product child page
- Learn highlighted when on an integrations child page
=> Added highlight in main nav to currently active section.

data/promos/newpromo.ts
Replace the content in the homepage promo to feature the DevEx survey
As temporary solution to feature newsworthy content on the homepage we are reusing the promo component
Local testing by browsing the site
=> Replacing promo content on homepage

data/markdown/partials/learn/getting-started/composable-dxp.md, data/markdown/partials/learn/getting-started/platform-dxp-development-frameworks.md, data/markdown/partials/learn/getting-started/platform-dxp.md, data/markdown/partials/learn/getting-started/product-features.md, data/markdown/partials/solution/commerce/ordercloud.md, data/markdown/partials/solution/commerce/sitecore-commerce.md, data/markdown/partials/solution/content-management/jss.md, data/markdown/partials/solution/content-management/sxa.md, data/markdown/partials/solution/content-management/web-cms.md, data/markdown/partials/solution/customer-data-management/cdp.md, data/markdown/partials/solution/dam-and-content-operations/content-hub.md, data/markdown/partials/solution/personalization-testing/personalize.md
For the `/learn` page and a group of product pages, I have added links to the new Sitecore Essentials course that is free and now available on learning.sitecore.com. There is only one 'pathway' that covers a lot of products, so I've tried to provide sub-bullets or descriptions where necessary to list the relevant topic/module that makes sense for that page.
For example, on the `/learn` page the Sitecore Essentials course shows up in all 4 "Getting Started" boxes, but I only list the modules that are appropriate for that box. Similarly, on the SXA page, I only mention the Introduction to SXA module. This pattern repeats across the product pages that are required.
This fixes #180, and is meant as an interim solution to get the free courses listed. We may need a new issue to further refine …
=> Added free Learning essentials course to Learn and product pages

data/markdown/partials/learn/integrations/content-hub.md, data/markdown/partials/solution/dam-and-content-operations/dam.md
There is a new Salesforce Commerce Cloud integration guide for the new Content Hub connector that is published in the documentation: https://docs.stylelabs.com/contenthub/4.1.x/content/integrations/salesforce-commerce-connector/salesforce-commerce-connector.html
This PR adds this to the list of 'integrations' for Content Hub on both the `/learn` page and the integrations list on the `/dam-and-content-operations/dam` page.
This raises awareness of the Content Hub integration capabilities. We should look at whether other connectors in that documentation should also be listed.
This is a markdown change only. Validated that the new items appear on local and Vercel, and validated that the links work going to the destination page.
=> Adding SF Commerce connector to integrations list

data/markdown/pages/solution/customer-data-management/index.md, data/markdown/pages/solution/customer-data-management/product/cdp/index.md, data/markdown/pages/solution/personalization-testing/index.md, data/markdown/pages/solution/personalization-testing/product/personalize/index.md
This has been done for the CDP product page, Personalize product page, and the parent landing pages for Customer Data Management and Personalization/Testing.
NOTE: I put #cdp first for the customer data management page, and put it second on Personalize as that product will actually be called "Sitecore Personalize", and #personalization is a more relevant tag. Currently, there is an issue where only the first tag seems to be displayed on the page (logged as issue #210)
In the configuration markdwon files for the pages, the tag #cdp was added to the stackexchange metadata property where present. A new stackexchange metadata property was added to the pages where there was not already a list configured, and #cdp was put as the value for that property.
This causes the StackExchange feed to …
=> Added #cdp tag to the SSE configs for CDP/Personalize pages

data/promos/newpromo.ts, next.config.js
Replacing the DevEx survey promo with VDD
Added stylelabs CDN url to next.config.js since DAM provided a public link with the stylelabs url.
DevEx survey has been featured for two weeks and has been closed.
Local and [Vercel staging environment](https://developer-portal-614588r7w-sitecoretechnicalmarketing.vercel.app/)
=> Virtual Developer Day promo

data/markdown/partials/trials/jss-connected-demo/exploring-code/graphql.md
Closes #216 as reported by the demo team. 
Path with capital S results in error
Local testing and [Vercel preview environment](https://developer-portal-nlw91hi0y-sitecoretechnicalmarketing.vercel.app/trials/jss-connected-demo/exploring-code/graphql)
=> Fixes #216 - Remove capital S from sitecore url path

.github/workflows/deploy.yml
Change in deploy workflow to run on pull_request_target event which is triggered by dependabot
PRs created by dependabot do not run in the context of the merge commit therefore has no access to the secrets stored in Github
Local testing using ACT,
=> Ensure dependabot has access to settings

data/promos/newpromo.ts
For pushing to production after the blog goes live on December 16th. This promotes the new blog on the community portal about the SSE announcement.
The promo card data has been updated from the Virtual Developer Day information to the SSE blog information. 
There is no open issue for this, this is related to marketing around an event. This supports highlighting developer content to developers.
Tested locally and on the [Vercel preview environment](https://developer-portal-g10tnbob2-sitecoretechnicalmarketing.vercel.app/)
=> Updating promo from VDD to SSE news

.vscode/settings.json
Removing color setting for VS Code
Unnecessary setting
Local VS Code environment
=> Removed VS Code color settings

components/integrations/sitecore-community/questions/SitecoreCommunityQuestions.tsx, scripts/page-info.ts
Fixes to query calls
- Fix copy-pasta error in static call to use correct key for sort
- Moved Axios call into useEffect to fire after set state action is complete
- Minor styling fix for when sort is present but not filter
https://github.com/Sitecore/developer-portal/issues/231
- Tested static locally by confirming the URL matches appropriate sort variable
- Tested dynamic locally using network tab and confirming correct query
=> Fixed errors in static and dynamic call to questions API.

data/markdown/pages/solution/commerce/index.md, data/markdown/pages/solution/commerce/product/discover/index.md, data/markdown/pages/solution/commerce/product/experience-commerce/index.md, data/markdown/pages/solution/commerce/product/ordercloud/index.md, data/markdown/pages/solution/content-management/index.md, data/markdown/pages/solution/content-management/product/experience-manager/index.md, data/markdown/pages/solution/customer-data-management/index.md, data/markdown/pages/solution/customer-data-management/product/cdp/index.md, data/markdown/pages/solution/customer-data-management/product/experience-platform/index.md, data/markdown/pages/solution/dam-and-content-operations/index.md, data/markdown/pages/solution/dam-and-content-operations/product/content-hub/index.md, data/markdown/pages/solution/dam-and-content-operations/product/dam/index.md, data/markdown/pages/solution/marketing-automation/index.md, data/markdown/pages/solution/marketing-automation/product/experience-platform/index.md, data/markdown/pages/solution/marketing-automation/product/send/index.md, data/markdown/pages/solution/personalization-testing/index.md, data/markdown/pages/solution/personalization-testing/product/experience-platform/index.md, data/markdown/pages/solution/personalization-testing/product/personalize/index.md
Configured the solution pages to show the latest questions (if available) from their respective sub forums on Sitecore Community 
Community integration was only used on homepage and community page. Solution pages where still a todo.
Local testing and Vercel preview environment
=> Configured community questions for solution pages

data/markdown/partials/learn/integrations/xm.md, next.config.js
- Added XM <-> CDP SmartHub link missed in previous commit. @dylanyoung-dev this should cover the missing items.
- Added 301 redirect from previous URL @markvanaalst, I think this is the first time we've had to change a URL and introduce a 301. Are you happy with the implementation in here?
=> Fixed issue with missing integration link, added 301 from previous URL

components/integrations/sitecore-community/SitecoreCommunity.api.ts, components/integrations/sitecore-community/blog/SitecoreCommunityBlog.tsx, components/integrations/sitecore-community/questions/SitecoreCommunityQuestions.tsx, scripts/page-info.ts
Fixes #247 - Adding created as the default sort option for announcements and blogposts.
Latest blogpost component on the homepage listed updated (but old) posts.
Local and [Vercel environment](https://developer-portal-qxurk1zd8-sitecoretechnicalmarketing.vercel.app/)
=> Adding created as default sort option

next.config.js
Adding config setting to allow SVG images used in the Nextjs image component
SVG images are not working currently
Local and [Vercel environment](https://developer-portal-3op4w701w-sitecoretechnicalmarketing.vercel.app/)
- [X ] Bug fix (non-breaking change which fixes an issue)
=> Allow SVG in Nextjs image component

data/markdown/pages/solution/dam-and-content-operations/product/content-hub/index.md, data/markdown/pages/solution/dam-and-content-operations/product/dam/index.md
The playlist ID value for the `youtube` metadata was updated to point to the newly created Content Hub playlist on Discover Sitecore.
Fixes issue #260 to update the playlist used for the Content Hub pages. All videos related to Content Hub are on this new playlist.
Tested locally and on Vercel preview environment to ensure that the new playlist displays on both the Content Operations and DAM pages.
=> Added new Content Hub playlist to CH pages

data/promos/newpromo.ts
For the newpromo.ts file, I updated the description, image, and link to refer to VDD being in the past and redirect to the YouTube video.
Fixes #262. Now that Virtual Developer Day is open, driving users to registration doesn't make much sense.
Tested this locally for the home page, and also on the Vercel preview environment. Checked that the correct image and text displayed and that the link goes to the correct video.
=> Updated home page promo to direct users to YouTube video

data/markdown/partials/integrations/blueprint-xm-smarthub-cdp.md
SmartHub CDP is a combination of Sitecore Personalize and Sitecore CDP.
Fix a typo in the description of SmartHub CDP.
Remove the SmartHub in one line, as it is not clear what SmartHub CDP is.
N/A
=> Typo in the SmartHub CDP description

data/markdown/partials/docs/cms/sitecore-content-hub.md, data/markdown/partials/solution/dam-and-content-operations/content-hub.md
Several links were reported as broken, and others that work go to the earlier version (4.1). These changes update all links to working 4.2 versions of the docs.
Not all doc links were updated across all pages. I fixed the reported ones on the Docs page, and then the matching ones on the Content Hub page. There may be others that also need to be fixed, or are out of date.
Content changes only. No local testing done. Tested on Vercel environment:
* [Docs page](https://developer-portal-a52f1mv73-sitecoretechnicalmarketing.vercel.app/docs)
* [CH page](https://developer-portal-a52f1mv73-sitecoretechnicalmarketing.vercel.app/dam-and-content-operations/content-hub#heading-user-documentation)
=> Updated Content Hub docs links to 4.2

src/common/page-info.ts
Fix the GitHub edit link for pages where no partials are being used (learning articles)
Local and [Vercel](https://developer-portal-47winyoct-sitecoretechnicalmarketing.vercel.app/learn/getting-started/introduction-to-composable-dxp)
=> Fix edit link

data/data-navigation.ts, data/markdown/pages/solution/content-management/product/xm-cloud/index.md, data/markdown/partials/learn/starter-kits/ordercloud.md, data/markdown/partials/learn/starter-kits/xm-cloud.md, data/markdown/partials/solution/content-management/xm-cloud.md, src/pages/learn/index.tsx
With the launch of XM Cloud, we need a page to hold all developer content and resources for people looking for information about the product. There is an XM Cloud Introduction article, but we need to have an official product resources page as well. This pull request is to add the necessary navigation and markdown partials to create that page, though some content needs GA before being able to be updated (like Docs links and Learning courses)
Additional work will be needed for these pages to be fully complete, but this should be good enough for a first launch and then we can iterate.
Fixes #309  
Tested locally and on Vercel preview environments.
=> 309 create product page for xm cloud

data/data-navigation.ts, data/markdown/partials/docs/cms/headless.md, data/markdown/partials/docs/cms/sitecore-experience-manager.md, data/markdown/partials/docs/cms/sitecore-xm-cloud.md, data/markdown/partials/learn/getting-started/composable-dxp.md, data/markdown/partials/solution/content-management/xm-cloud.md, src/pages/docs.tsx
The /learn, /docs, and XM Cloud product page are now updated to link to the documentation on the new XM Cloud docs pages. The menu was slightly updated as well.
This fixes #330 .
Tested locally on developer environment and reviewed on Vercel preview environment.
=> Add XM Cloud docs to the Developer Portal

data/markdown/pages/solution/devops/product/managed-cloud/index.md
Playlist was created on Discover Sitecore, metadata was updated for the Managed Cloud page to display the YouTube playlist on the page.
Fixes #255 
Tested on Vercel preview site to ensure the playlist displays.
=> Adding Managed Cloud playlist to the metadata

src/layouts/components/footer/Footer.tsx
At request of sitecore.com team, updating the footer link to Legal from /trust to /legal. 
⚠This PR should not be published to production until sitecore.com/legal has been published! ⚠
Fixes #344 
Checked on local and preview site, but sitecore.com/legal has not been published so a 404 is found. Needs to be revalidated before merging once sitecore.com/legal publishes.
=> Updated footer Legal link from /trust to /legal

data/markdown/partials/solution/commerce/ordercloud.md
Removed old OC documentation link.
=> Remved old OC doc link

data/markdown/partials/solution/commerce/ordercloud.md
Adding a link to the new SItecore OrderCloud documentation page, showing how to share events with Sitecore Discover and SItecore Send.
=> Add documentation link for Event sharing between OC, Discover & Send

apps/devportal/data/newsletters/2022/12.json, apps/devportal/data/newsletters/2023/01.json, apps/devportal/data/newsletters/2023/02.json, apps/devportal/src/common/static-paths.ts, apps/devportal/src/pages/newsletter/index.tsx
The developer portal was missing December 2022, January 2023, and February 2023. Also, sorting was fixed on /newsletter page and nav bar when reading newsletters.  Adding new year of 2023 was not handled properly and also sorting changes need to be made now that more than the max 12 newsletters in navbar are present. 
Manual testing on branch
=> Adding missing Sitecore Developer Newsletters - And Fixing Sorting

apps/devportal/data/markdown/partials/solution/content-management/xm-cloud.md, packages/ui/components/cards/Repository.tsx
Fixes #398 
Multiple frameworks are supported by using the | separator in the framework property 
`<Repository framework="Nextjs|DotNET" .... />`
Local
=> Support for multiple frameworks in repository

apps/devportal/data/markdown/pages/home/index.md, apps/devportal/src/components/changelog/ChangelogList.tsx, apps/devportal/src/pages/changelog/[product]/[entry].tsx, apps/devportal/src/pages/changelog/[product]/index.tsx, apps/devportal/src/pages/changelog/index.tsx, packages/ui/components/buttons/EditButton.tsx, packages/ui/components/common/ProductImage.tsx, packages/ui/components/common/ProductLogo.tsx, packages/ui/components/heros/Hero.styles.css, packages/ui/components/heros/Hero.tsx, packages/ui/components/heros/ProductHero.tsx, packages/ui/styles/buttons.css
This PR introduces new functionality for the Hero banner used on all pages. 
- Visual changes to align hero with sitecore.com style
- Using product images as title when image specified (renders title for screen readers)
- Introduced option to add "children" to the hero component for custom messaging
- Adds powered by CH ONE to Changelog
Local and [Vercel](https://developer-portal-git-feature-cc06b5-sitecoretechnicalmarketing.vercel.app/)
The Hero banner has three different "modes"
- **Simple version with title and description** [(Example)](https://developer-portal-git-feature-cc06b5-sitecoretechnicalmarketing.vercel.app/learn)
In desktop mode the description is shown first, all caps and with a wider character spacing to match the style used on sitecore.com
- **Product version** …
=> Hero banner improvements

apps/devportal/src/components/integrations/sitecore-search/SearchFacets.tsx
Fixes invalid selected facet value state in search results page
- Open https://developer-portal-git-sitecore-search-sitecoretechnicalmarketing.vercel.app/search?q=dxp
- Check `Type -> Video`
- Wait until results for the selected facet are rendered
`Type -> Video` should be still checked
`Type -> Video` is un-ckecked
An index `key` is used for facet components causing wrong node mapping by the VirtualDOM after re-rendering the received facets (see https://articles.wesionary.team/using-index-as-a-key-is-an-anti-pattern-in-react-8e5db3aea3a9)
Use the `facet` name as the facet component `key`
=> Fixes invalid selected facet value state

apps/devportal/src/pages/changelog/[product]/[entry].tsx, apps/devportal/src/pages/changelog/[product]/index.tsx
The title for the Changelog listing and detailed entry page read "Release Notes" instead of "Changelog". This change aligns the page's <title> with the H1 hero title.
Tested on the Vercel branch.
=> Updating title for changelog to match the H1

apps/devportal/src/components/changelog/ChangeLogItem.tsx, apps/devportal/src/pages/changelog/[product]/[entry].tsx, packages/sc-changelog/types/common/media.ts
Adds behavior that allows the user to click the changelog image to load it full with in a modal popup
Local and [Vercel](https://developer-portal-git-feature-b12715-sitecoretechnicalmarketing.vercel.app/changelog)
=> Add image modal for changelog images

apps/devportal/src/components/changelog/ChangelogItemMeta.tsx
Underline link to product page on changelog entry
Local
=> add underline to product in meta info

packages/sc-changelog/lib/search.ts
Put back the date restriction on GraphQL request
Local
=> Date restriction in GraphQL search request

apps/devportal/data/markdown/pages/solution/content-management/product/search/index.md
Removes the incorrect YouTube playlist from the Sitecore Search product page. There isn't currently a PlayLIst for search videos, once one is created then we can add this back in.
- [ x I have read the Contributing guide.
Closes #441
=> Remove Incorrect YouTube Playlist from Sitecore Search product page

packages/sc-changelog/utils/stringUtils.ts
Allows for periods in changelog urls (fixes #461)
Local and [Vercel](https://developer-portal-git-issue-46-bab2ae-sitecoretechnicalmarketing.vercel.app/changelog)
=> Allow periods in changelog url

apps/devportal/src/pages/_app.tsx
Fixes current bug where homepage is adding a trailing `/` to the Search Entity Page View call, meaning its ID doesn't match.
Changed to drop all trailing slashes.
=> Removed trailing slashes from Search Page View calls

apps/devportal/src/components/integrations/sitecore-search/PreviewSearchInput.tsx, apps/devportal/src/components/integrations/sitecore-search/SearchResults.tsx
Currently we're only triggering Entity View events for entities hosted on the developer portal. This change also fires that events for search results that are clicked on, hosted on external sources.
We have to ensure we don't fire this event on clicks for documents from the dev portal though as we'll end up double tracking the event then.
Closes #474
=> Triggering Search Entity Click Event for external sources

apps/devportal/package.json, package-lock.json
Bumped the SDK version for Search, this adds a fix to ensure that facets matches the 'and/or' rules defined in the CEC. The previous version was hardcoded to 'and'
=> Bumped Search SDK version

apps/devportal/package.json, package-lock.json
Bumped minor version of the Search SDK. This introduces support for the APJ region for the SDK. We had an issue where a partner here wanted to test the developer portal against their Search instance in the APJ region and could not.
=> Bumped minor version of Search SDK

apps/devportal/src/pages/changelog/current.tsx
Remove link to what's new pages for XM Cloud
Local
=> Remove xm cloud from list

apps/devportal/package.json, apps/devportal/src/components/changelog/ChangeLogItem.tsx, apps/devportal/src/components/common/SocialShare.tsx, apps/devportal/src/pages/changelog/[product]/[entry].tsx, package-lock.json, packages/sc-changelog/utils/urlBuilder.ts
Adds social buttons to the changelog entries for sharing purposes (#472) 
Local
=> Use next-share for social sharing

apps/devportal/src/common/search.ts, apps/devportal/src/components/integrations/sitecore-search/SearchInputSwitcher.tsx, apps/devportal/src/pages/_app.tsx
Enabled graceful fallback when Search ENV VARS aren't populated.
Closes #489
=> Configured Search to be gracefully disabled when ENV VARS are missing

packages/ui/components/sitecoreCommunity/SitecoreCommunityBlogOrQuestion.tsx
On the current production, the links for the blog articles on the home page do not work. They are all relative and do not go to the Community site. Other blog listing components use a constant for the Community link, and this PR is intended to bring that into alignment.
Fixes #507 
Testing on preview Vercel environment to ensure links work.
=> Attempting to align "Latest Blogs" link generation 

apps/devportal/data/markdown/partials/solution/content-management/xm-cloud.md
Added links to XM Cloud courses to replace the "COMING SOON!" text. Uses the 'cards', similar to how documentation is listed.
Tested locally and on Vercel.
=> Adding links to XM Cloud dev courses

apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud-introduction/index.md, apps/devportal/data/markdown/partials/learn/faq/xm-cloud-embedded-personalization/feature-matrix.md, apps/devportal/data/markdown/partials/learn/faq/xm-cloud-recommended-practices/getting-started.md, apps/devportal/data/markdown/partials/learn/faq/xm-cloud/development.md
Developers learning about XM Cloud are currently directed to XM and XP docs, instead of XM Cloud. This causes the developer to get lost in multiple doc sites. This change attempts to correct links to reference XM Cloud versions of the docs and removes links that would take the user to XM-only docs unless relevant.
Fixes #515 
Tested locally and on Vercel.
=> Updated docs to reference XMC instead of XP

apps/devportal/data/markdown/partials/learn/faq/xm-cloud/rendering.md
The current XMC FAQ incorrectly states that only the NextJS SDK is supported. This PR changes this to correctly state that the NextJS SDK is the preferred SDK, but that all of them are supported.
This change has been approved by Justin
Closes #519
=> Updated FAQ for XM Cloud

apps/devportal/data/markdown/partials/learn/faq/xm-cloud/upgrades.md
Removed confusing reference to XM in the XM Cloud FAQ. No longer implying there is a possibility for automatic updates of XM. Also added links to existing docs about upgrades instead of "more clarification after Symposium 2022"
Tested on Vercel preview site.
=> Add link to XM Cloud upgrades docs

apps/devportal/data/markdown/partials/solution/commerce/ordercloud.md
Fixes broken learning link on OrderCloud product page
Closes #532
=> Updated OC Learning courses link

packages/ui/components/integrations/sitecoreCommunity/SitecoreCommunityNewsOrEventItem.tsx
The title text in Community News was hardcoded to black. This was difficult to read in dark mode. The default color when no color was set is better.
But on a different note, the "Community News" gets extremely infrequent updates. A single news item in 2023 should it be removed? Or should we make an effort to make more news announcements? 
Improve Readability in dark mode.
Visual
=> Remove hardcoded black text, default color works in light and dark mode

apps/devportal/data/markdown/pages/content-management/xm-cloud.md
Added 3 new links to the XM Cloud product page. Also updated the title for 'Other Learning' to be about Community Learning Resources. 
The new links will support the new XM Cloud developer exam and allow students to find the course, study guide, and exam.
Tested locally and on preview site.
=> Adding new links to support XM Cloud dev exam

apps/devportal/src/pages/_app.tsx, packages/ui/components/social/SocialShare.tsx
Adds "copy link to clipboard" functionality to Changelog
Fixes #555 
Local and [Vercel](https://developer-portal-git-feature-f2f093-sitecoretechnicalmarketing.vercel.app/changelog)
=> Add copy to clipboard to changelog

apps/devportal/data/markdown/pages/customer-data-management/cdp.md
Been asked a few times about CDP mobile tagging. Adding the link to the dev portal page as a Resource.
Tested on Vercel
=> Adding in link to the Mobile App Tagging Overview doc on the knowledge base

apps/devportal/src/pages/_app.tsx
Currently, there is an issue with how we're conditionally creating/recreating the WidgetProvider used by the Search SDK. This is causing the Widget data in the request to be doubled for each request. Moving the definition outside MyApp fixes this issue.
Closes #561
=> Fixed issue where Search API requests were doubling Widget data

apps/devportal/src/pages/api/changelog/v1/indexing.ts
In order to build out the ChangeLog API with Search, it's going to be simpler to include all of the product information in the response that in Indexed, instead of having to request it again from CH-ONE.
This change will enable that, and will make it simpler to switch the UI over to be based on Sitecore Search
=> Extended the Changelog API to include full product info

apps/devportal/data/markdown/pages/content-management/xm-cloud.md, apps/devportal/data/markdown/pages/learn/getting-started/migrating-to-the-sitecore-composable-dxp/index.md
Now that the migration tool download is available, we need to make it available on the migration resources page. 
**NOTE:** At the same time, a small fix to the title and link to the tool on the XMC product page was made.
Tested locally and on Vercel that the page loads and that the links work.
=> Add XMC migration tool to migration resources page

apps/devportal/data/markdown/pages/downloads/index.md, apps/devportal/src/components/navigation/Footer.tsx, apps/devportal/src/layouts/ChildOverviewPage.tsx, apps/devportal/src/layouts/Layout.tsx, apps/devportal/src/layouts/ThreeColumnLayout.tsx, apps/devportal/src/pages/_app.tsx, apps/devportal/src/pages/_document.tsx
Fixes #575 
Adding a (temporary) downloads page that lists sub items. Will be replaced with proper page once dev migration is completed. PR also includes a fix to make the footer stick to bottom.
Local and [Vercel](https://developer-portal-git-issue-57-cecb24-sitecoretechnicalmarketing.vercel.app/downloads)
=> Add downloads page

apps/devportal/data/markdown/pages/community.md
Updated the promo at the top of the Community page to highlight the SUGCON events.
Tested on Vercel (local is currently broken)
=> Promote SUGCON events on Community page

apps/devportal/data/markdown/pages/content-management/headless.md, apps/devportal/data/markdown/pages/trials/index.md, apps/devportal/data/markdown/pages/trials/jss-connected-demo/index.md, apps/devportal/data/markdown/partials/solution/content-management/jss.md
As part of decommissioning the old JSS Trial, this Pull Request removes all references to the links for the current trial. The forms are still live on sitecore.com at this moment, but we are slowly removing the paths to getting to the form in advance of removing the forms.
Tested locally. Small content changes only.
=> Remove JSS trial references

apps/devportal/src/components/markdown/MarkdownContent.tsx
Fixes #604 - Use full version of syntax highlighter to resolve [bug](https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/263)
Local and [Vercel](https://developer-portal-git-issue-60-37a375-sitecoretechnicalmarketing.vercel.app/contribute/components)
=> Use full version of syntax highlight

apps/devportal/src/components/common/contribute.tsx, apps/devportal/src/components/navigation/ChildNavigation.tsx, apps/devportal/src/lib/theme/proseTheme.ts
This PR adds;
- Menu item clickable to expand subitems
- Styling improvements to `<code />` element
- Have the recipe contribution component use the Alert component instead of card
Local and [Vercel](https://developer-portal-ki66w0292-sitecoretechnicalmarketing.vercel.app/learn/accelerate/xm-cloud/implementation/information-architecture/wildcard-pages)
=> UI updates for the Accelerate content

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json, apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-experience/branching-strategy.md, apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/devops.md, apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/project-solution-setup.md, apps/devportal/data/markdown/pages/learn/getting-started/managed-cloud-with-containers/index.md
Fix for casing should be brought into Accelerate branch as well to correct issues in the in-progress recipes.
Any text that used incorrect casing for DevOps ('devops' or 'Devops') was updated. This impacted Accelerate recipes and Managed Cloud guides.
Reviewed on preview environment in Vercel
=> Replaced Devops and devops with DevOps

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-experience/branching-strategy.md
Update Accelerate document covering Monorepos, to include the requirement all of the heads running in the Monorepo to all be on the same version of Node.
=> Updated Monorepo listing to include restriction on node version differences

apps/devportal/src/components/navigation/InPageNav.tsx, apps/devportal/src/layouts/ThreeColumnLayout.tsx
This PR replaces the inpage sidebar on smaller screens with a icon
Local and [Vercel](https://developer-portal-git-inpagenav-width-sitecoretechnicalmarketing.vercel.app/learn/accelerate/xm-cloud)
=> Replace InPageNav sidebar with icon on smaller screens

apps/devportal/src/components/changelog/ChangelogItemMeta.tsx
Small PR that changes the changetype display for Changelog entries from Tag to Badge and makes it consistent with other displays
Local
=> Changelog meta info switch tag to badge

packages/ui/components/social/SocialShare.tsx
Add additional social share buttons to the Changelog to match the social icons that will be available in the Migration Advisor. 
Viewable: https://developer-portal-git-social-s-2c454a-sitecoretechnicalmarketing.vercel.app/changelog
Manually tested
=> Add social media sharing buttons and popover to Changelog

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/sitemap.md, apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json, apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/information-project-architecture/publishing-to-edge.md
[Link to page on deployed vercel site](https://developer-portal-git-fork-crh-ffdb7c-sitecoretechnicalmarketing.vercel.app/learn/accelerate/xm-cloud/implementation/sitemap)
=> ACC-35 Add "Sitemap" page to xmc accelerate docs

apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update2/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update3/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/102/Sitecore_Experience_Platform_102/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/102/Sitecore_Experience_Platform_102_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/103/Sitecore_Experience_Platform_103/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/103/Sitecore_Experience_Platform_103_Update1/index.md
On each applicable Sitecore XP download page, updated the link to its latest Container Package, for the given SXP 10.x.y patch release.
Customer satisfaction. To avoid confusion where some links were old, some newer, some jumped to a new SXP patch release, some did not.
Based on feedback from Sitecore Prof. Services, on dev.sitecore.net.
Copy/pasted every new link to a browser. Visually inspected that intended link was reached.
For those links that included a change in link format, confirmed new links worked.
=> Update links from SXP download pages to their corresponding container packages

packages/ui/components/integrations/stackexchange/StackExchangeFeed.tsx
The link on the component is broken because of an extra } character in the markup. This PR removes that character. Fixes #687 
Tested locally and on Vercel preview site.
=> Removing extra character in SSE link on StackExchangeFeed component

README.md, apps/devportal/data/markdown/pages/contribute/index.md
The current links to the Code of Conduct file in GitHub are broken and show a 404.
In VS Code markdown Preview and on Vercel preview site
=> Fixed link references to Code of Conduct file

apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/100/Sitecore_Experience_Platform_100/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/100/Sitecore_Experience_Platform_100_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/100/Sitecore_Experience_Platform_100_Update2/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/100/Sitecore_Experience_Platform_100_Update3/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update2/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update3/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/102/Sitecore_Experience_Platform_102/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/102/Sitecore_Experience_Platform_102_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/103/Sitecore_Experience_Platform_103/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/103/Sitecore_Experience_Platform_103_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/Sitecore_Device_Detection_Services_Usage_Policy.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/Sitecore_IP_Geolocation_Usage_Policy.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/Sitecore_xDB_Cloud_Usage_Policy.md
Changes:
- Tidied doc formatting that got messed up after porting over from dev.sitecore.net
- Removed the 2015 document creation date, because it adds no value, and looks bad on Sitecore.
- Removed links from SXP release download pages to one policy that no longer applies (due to being a discontinued offering).
Why:
- Tidying prior to releasing SXP 10.4, where we want the download page to appear accurate and updated.
- Also cleaning up some former releases, which was easy to do within this same PR.
- These trivial updates all contribute to the credibility of our Platform DXP program.
- First confirmed that these old policy docs are not actively owned or managed by anyone, so its up to us to keep them relevant.
- Observed the doc edits in a markdown viewer panel of Notepad++.
=> Tidy SXP policy references

apps/devportal/data/markdown/pages/downloads/Sitecore_Installation_Framework/2x/Sitecore_Installation_Framework_200/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Installation_Framework/2x/Sitecore_Installation_Framework_210/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Installation_Framework/2x/Sitecore_Installation_Framework_220/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Installation_Framework/2x/Sitecore_Installation_Framework_230/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Installation_Framework/2x/Sitecore_Installation_Framework_240/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Installation_Framework/2x/Sitecore_Installation_Framework_240/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Installation_Framework/index.md, apps/devportal/data/markdown/pages/downloads/index.md
- Added new release download SIF 2.4.0. Why: It was recently added to dev.sitecore.net. Is needed with forthcoming SXP 10.4 release. Needed to do a dry run release test, prior to the big SXP 10.4 release coming in late April!
- Minor tidying of release notes for previous SIF 2.x releases. Why: Some got messed up a little when porting from dev.sitecore.net. Some were already messy in dev.sitecore.net.
- Viewed documentation results in the Notepad++ markdown viewer panel.
- Did page by page comparisons between my new .md file and page in dev.sitecore.net
=> Add new SIF 2.4.0 release, tidy previous SIF release notes

apps/devportal/src/components/markdown/MarkdownContent.tsx, packages/ui/src/theme/proseTheme.ts
This PR removes the default columns width for markdown tables and adds dark mode enhancements
Local and [Vercel](https://developer-portal-git-issue-md-table-sitecoretechnicalmarketing.vercel.app/)
=> Markdown table improvements

apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/100/Sitecore_Experience_Commerce_100/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/101/Sitecore_Experience_Commerce_101/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/102/Sitecore_Experience_Commerce_102/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/103/Sitecore_Experience_Commerce_103/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/80/Commerce_Server_112_Initial_Release/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/80/Commerce_Server_112_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/80/Sitecore_Commerce_80_Connect/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/80/Sitecore_Commerce_80_powered_by_Commerce_Server_Initial_Release/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/80/Sitecore_Commerce_80_powered_by_Commerce_Server_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/80/Sitecore_Commerce_80_powered_by_Microsoft_Dynamics_Initial_Release/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/80/Sitecore_Commerce_80_powered_by_Microsoft_Dynamics_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/81/Sitecore_Commerce_81_Connect/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/81/Sitecore_Commerce_81_powered_by_CS/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/81/Sitecore_Commerce_81_powered_by_Microsoft_Dynamics_Initial_Release/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/81/Sitecore_Commerce_Server_113/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/82/Commerce_Server_114/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/82/Sitecore_Commerce_82_Connect/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/82/Sitecore_Commerce_82_powered_by_Commerce_Server/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/82/Sitecore_Commerce_82_powered_by_Microsoft_Dynamics/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/821/Sitecore_Commerce_821/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/821/Sitecore_Commerce_821_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/821/Sitecore_Commerce_821_Update2/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/821/Sitecore_Commerce_821_Update3/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/90/Sitecore_Experience_Commerce_90_Initial_Release/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/90/Sitecore_Experience_Commerce_90_Update1/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/90/Sitecore_Experience_Commerce_90_Update2/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/90/Sitecore_Experience_Commerce_90_Update3/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/91/Sitecore_Experience_Commerce_91_Initial_Release/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/92/Sitecore_Experience_Commerce_92_Initial_Release/index.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Commerce/93/Sitecore_Experience_Commerce_93_Initial_Release/index.md
Fixed broken link on all Experience Commerce download pages, carried over from dev.sitecore.net.
Copy/pasted broken and fixed links to a fresh browser.
Inspected PR line by line, compared against each XC download page.
=> Fix broken links XC download pages

apps/devportal/data/markdown/pages/downloads/manifest.json, apps/devportal/src/components/navigation/BreadcrumbNav.tsx, apps/devportal/src/components/navigation/SidebarNavigation.tsx, apps/devportal/src/components/navigation/SidebarSearch.tsx, apps/devportal/src/layouts/ArticlePage.tsx, apps/devportal/src/lib/interfaces/page-info.ts
This PR adds a filter to the sidebar on the [download pages](https://developer-portal-1057hpalq-sitecoretechnicalmarketing.vercel.app/downloads).
Local and [Vercel](https://developer-portal-1057hpalq-sitecoretechnicalmarketing.vercel.app/downloads)
=> Add filter to downloads sidebar

README.md, apps/devportal/data/markdown/pages/contribute/index.md
The current links to the Code of Conduct file in GitHub are broken and show a 404.
Local
=> Fix link references to Code of Conduct

apps/devportal/data/markdown/pages/newsletter/2024/02.md
Fixes #705 to provide correct URL for mentorship article: https://www.mastertoweb.com/blog/sitecore-mentor-program/
On [Vercel preview site](https://developer-portal-git-705-inco-5eef1d-sitecoretechnicalmarketing.vercel.app/newsletter/2024/02) and local
- [] Bug fix (non-breaking change which fixes an issue)
=> Fixing URL to mentor article

packages/changelog/src/lib/common/api.ts
Allows for sites to run without a .env file or without the CH ONE configurations. This reverts to earlier behaviour where the Changelog is silently degraded.
Tested locally and on Vercel
=> Remove exception throwing and replace with console warning

apps/devportal/src/layouts/ArticlePage.tsx, apps/devportal/src/layouts/DefaultContentPage.tsx
This PR fixes the issue that the InPageNav does not reload after route change
=> Reload InPageNav after route change

apps/devportal/data/markdown/pages/downloads/xDB_to_CDP_Migration/index.md
The docs link was wrong and should go to: https://doc.sitecore.com/xp/en/developers/104/sitecore-experience-platform/the-xdb-to-cdp-migration-tool.html
Locally and on Vercel
=> Fix xDB to CDP migration tool docs link

apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud/tutorials/datasources.md, apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud/tutorials/setup-xm-cloud.md
Fixes #776 reported issue
Local and [on Vercel](https://developer-portal-git-776-upda-cd9918-sitecoretechnicalmarketing.vercel.app/learn/getting-started/xm-cloud/tutorials/setup-xm-cloud)
Ensured pages loaded and the word 'Press' was not in the tutorial.
=> Update "Press" to "Click" for button instructions

apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud/tutorials/create-a-component.md, apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud/tutorials/datasources.md
This PR adds the right menuOrder to the frontmatter of the article. Fixes the wrong order in the overview page.
Local and [Vercel](https://developer-portal-git-content-b1f8ef-sitecoretechnicalmarketing.vercel.app/learn/getting-started/xm-cloud/tutorials)
- [X ] I have read the Contributing guide.
=> Add frontmatter menuOrder to create component and datasource tutorial

apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104/index.md
- Updated description of the *Sitecore Azure Toolkit Resources* package on the SXP 10.4 download page, to identify that it has been patched and republished.
- Updated this on both the SXP 10.4 download page, and its Release Notes page.
- This accompanies a PR committed to Main just yesterday, which addressed accompanying Azure App Service packages. 
- tested on localhost:3000
=> Patched SAT Resources download package to replace incomplete Application Insights configuration

apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update1/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update2/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update3/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/102/Sitecore_Experience_Platform_102/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/102/Sitecore_Experience_Platform_102_Update1/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/103/Sitecore_Experience_Platform_103/Release_Notes.md, apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/103/Sitecore_Experience_Platform_103_Update1/Release_Notes.md
- Added the build number to the release notes of each SXP release, starting with SXP 10.1 - the release where the platform pre-releases approach was introduced.
- Driven by customer support ticket and ADO work item #610920, to improve the clarity of the baseline release against which cumulative hotfixes are compared. 
- Tested locally
=> Add release build number to SXP release notes

apps/devportal/data/markdown/pages/commerce/experience-commerce.md, apps/devportal/data/markdown/pages/content-management/experience-manager.md, apps/devportal/data/markdown/pages/devops/containers.md, apps/devportal/data/markdown/pages/devops/developer-collection.md, apps/devportal/data/markdown/pages/devops/managed-cloud.md, apps/devportal/data/markdown/pages/devops/sitecore-install-framework.md, apps/devportal/data/markdown/pages/learn/getting-started/managed-cloud-with-containers/index.md, apps/devportal/data/markdown/pages/marketing-automation/experience-platform.md, apps/devportal/data/markdown/partials/docs/cms/headless.md, apps/devportal/data/markdown/partials/docs/cms/sitecore-experience-manager.md, apps/devportal/data/markdown/partials/docs/commerce/sitecore-experience-commerce.md, apps/devportal/data/markdown/partials/docs/customer-data-management/sitecore-experience-platform.md, apps/devportal/data/markdown/partials/docs/marketing-automation/sitecore-experience-platform.md, apps/devportal/data/markdown/partials/docs/personalization/sitecore-experience-platform.md, apps/devportal/data/markdown/partials/learn/getting-started/platform-dxp-development-frameworks.md, apps/devportal/data/markdown/partials/learn/getting-started/platform-dxp.md, apps/devportal/data/markdown/partials/learn/getting-started/product-features.md, apps/devportal/data/markdown/partials/solution/content-management/headless-dot-net.md, apps/devportal/data/markdown/partials/solution/content-management/jss.md, apps/devportal/data/markdown/partials/solution/content-management/sxa.md, apps/devportal/data/markdown/partials/solution/content-management/web-cms.md, apps/devportal/data/markdown/partials/solution/customer-data-management/reference-data-service.md, apps/devportal/data/markdown/partials/solution/customer-data-management/web-tracking.md, apps/devportal/data/markdown/partials/solution/customer-data-management/xconnect.md, apps/devportal/data/markdown/partials/solution/customer-data-management/xdb.md, apps/devportal/data/markdown/partials/solution/marketing-automation/sitecore-xp-marketing-automation.md, apps/devportal/data/markdown/partials/solution/personalization-testing/federated-experience-manager.md, apps/devportal/data/markdown/partials/solution/personalization-testing/segmentation-and-conditions.md, apps/devportal/data/markdown/partials/solution/personalization-testing/universal-tracker.md
This PR updates all links to the documentation site and replaces any version specific URLs with the 'latest' version
Local
=> Replace version specific with latest in docs urls

packages/changelog/src/changelog.ts
This PR fixes an issue with the single product RSS feeds for the changelog
=> Update getEntriesByProduct to accept an array of product IDs

data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-planning/index.md, src/components/navigation/ScrollToTop.tsx, src/layouts/Layout.tsx, src/layouts/Sidebar.tsx, src/layouts/ThreeColumnLayout.tsx
This PR removes the sticky sidebar on three column pages (download/accelerate etc) and adds a scroll to top button instead
=> Remove sticky sidebar

data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1000/Release_Notes.md, data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1010/Release_Notes.md, data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1020/Release_Notes.md, data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1030/Release_Notes.md, data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1040/Release_Notes.md
Restore release notes for publishing service 10.x
Local
=> Restore release notes

data/markdown/pages/learn/accelerate/xm-cloud/implementation/information-architecture/workflow.md
Added information on how to add _PerSiteStandardValues base template to allow components to appear in the site standard values dialog box.
=> Jl workflow update rcps 66

data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/setup-content-serialization.md
Updated file paths and text changes based on new foundation head repo
=> Updated file paths and text changes based on new foundation head repo
