Sitecore/developer-portal

components/searchBox.tsx
package-lock.json
package.json
pages/_app.tsx

Added react-id-generator so we can have unique IDs generated in the component lifecycle and be SSR friendly.

Component Unique IDs with react-id-generator

---

components/helper/Container.tsx
components/layout/Layout.tsx

Pointing to `temp` until we get this merged to main.
Added Container component, only included it in `Layout` for now, figured we'd add it to other stuff as we style layouts/pages.
It has the ability to accept different sizes and such, but only has one viable size right now as that's all we have in the wires. But good to be flexible.

Added container helper component.

---

components/helper/SvgIcon.tsx
components/helper/icons/icon--quick-links.tsx
components/site/Nav/Nav.tsx
components/site/Nav/NavMenu.tsx
data/data-navigation.ts

**NOTE**: Opening against temp for now, will switch to main after current PR is merged.
Includes UX-suggested UI improvements to navigation:
- Remove "Quick Links" from mobile navs, embedded directly into menu
- Remove "Navigate by:" label

Updating nav with UX review improvements.

---

package.json

Opening against `temp` until we get it merged into main.
Add this as `.git/hooks/pre-push`
```
#!/bin/bash
npm run pre-push
```
Might need to chmod that file to make sure it's executable.

Added pre-push TS check.

---

components/integrations/stackexchange/StackExchange.api.ts
components/integrations/youtube/YouTube.api.ts
components/integrations/youtube/YouTubeFeed.tsx
data/markdown/pages/discover/index.md
data/markdown/pages/home/index.md
data/markdown/pages/learn/index.md
interfaces/integrations.ts
interfaces/page-info.ts
next.config.js
scripts/page-info.ts

Opening against parent branch until everything gets merged down to keep review succinct.
Added YouTube API MVP. Will require the appropriate YOUTUBE_API_KEY in a .env file to work will also require a restart of any running dev builds as next config changed.
If we don't need to use the thumbnails, we don't need to have this Next config. Open question out to Sydney about it. Going to add a ticket to the board.

Added YouTube API MVP.

---

components/helper/TextLink.tsx
components/heros/Hero.tsx
components/integrations/youtube/YouTubeFeed.tsx
components/layout/GenericContentPage.tsx
components/lists/CategoryTileList.tsx
components/lists/CommunityList.tsx
components/site/Footer/Footer.tsx
data/data-community-list.ts
interfaces/integrations.ts
pages/index.tsx

Cleaned up some margins on components and general spacing, styled the YouTube widget, added a text link helper and cleaned up the home page.

Homepage Cleanup, Spacing Cleanup, YouTube Styling

---

components/cards/PromoCard.tsx
components/layout/InPageNav/InPageNav.tsx
components/layout/Layout.tsx
pages/_app.tsx
styles/_base.css
styles/_utilities.css
tailwindcss-custom-types.ts

- Updated app so smooth scroll is temporarily disabled on route changes
- Added a transition to the `InPageNav` component so it smoothly transitions as the nav does
- Updated the auto focus on route changes to focus to a `sr-only` `anchor` at the top of the `<main>` content so we don't have to contend with scroll position on route changes.

Scrolling Fixes - Improvements

---

pages/404.tsx

There's an SVG on the SC main 404 page, but our Hero wouldn't want to play nicely with it. Decided not to modify the hero to accommodate the 404.

Added custom 404 page.

---

data/data-navigation.ts

Added deeplinks to DevOps content into DevOps solultion menu as discussed.

Extended main nav to have deeplinks to DevOps content

---

data/data-navigation.ts
data/markdown/partials/solution/content-management/headless-dot-net.md
data/markdown/partials/solution/content-management/jss.md
data/markdown/partials/solution/content-management/sxa.md
data/markdown/partials/solution/content-management/web-cms.md
data/markdown/partials/solution/customer-data-management/reference-data-service.md
data/markdown/partials/solution/customer-data-management/web-tracking.md
data/markdown/partials/solution/customer-data-management/xconnect.md
data/markdown/partials/solution/customer-data-management/xdb.md
data/markdown/partials/solution/devops/containers.md
data/markdown/partials/solution/devops/sitecore-install-framework.md
data/markdown/partials/solution/marketing-automation/sitecore-xp-marketing-automation.md
data/markdown/partials/solution/personalization-testing/segmentation-and-conditions.md
data/markdown/partials/solution/personalization-testing/universal-tracker.md

I've added links to downloads in the menu and in relevant MD files. 
Fixes  #53

Downloads links in menu and content

---

components/site/Footer/Footer.tsx
data/data-navigation.ts

Removed Get Help from navigation

---

scripts/page-info.ts

Added an or check for CR endings (works for CRLF endings too)

Added support for carriage return line endings.

---

data/promos/learning-at-sitecore.ts
data/promos/mvp.ts
data/promos/sitecore-support.ts

Updated 3 promo cards to use images from the DAM.
Fixes #82 
Fixes #83 
Fixes #84

Migrating promos to DAM

---

data/markdown/partials/integrations/blueprint-xm-cdp.md

Populated XM <-> CDP Blueprint

---

data/markdown/pages/integrations/send-ch/index.md
data/markdown/partials/integrations/blueprint-send-ch.md

Updated Send <-> CH Blueprint to match heading structure laid out by @jst-cyr in #89

Updated heading structure & title for send <-> ch blueprint

---

data/markdown/pages/integrations/send-oc/index.md
data/markdown/partials/integrations/blueprint-send-oc.md
data/markdown/partials/learn/integrations/orderCloud.md
data/markdown/partials/learn/integrations/send.md
pages/learn/index.tsx
pages/learn/integrations/index.tsx

Created the content for the Send <-> OC Blueprint. This follows the heading structure laid out by @jst-cyr in  #89

Created the Send <-> OC Blueprint content

---

components/layout/InPageNav/InPageNav.tsx
components/site/Nav/Nav.tsx
components/site/Nav/NavMenu.tsx
styles/_utilities.css
tailwind.config.js

- Updated prose to use `theme` variables for `pre` elements
- Updated prose to use `theme` variables for inline `code` elements
- Updated `InPagNav` to have appropriate top values after search was removed, updated all relevant `@TODO` statements with explanation.

Bug/code pre prose fix, InPagNav Update

---

data/markdown/partials/solution/content-management/edge-xm.md

* completed incomplete sentence
* removed link to experimental JSS SSR sample
* added additional helpful links

Updates to Edge XM content

---

public/robots.txt

Updated robots.txt to allow all search crawlers full access to the site.
We can teak this to restrict certain areas down the track as required.
closes #112

Updated robots.txt to allow all crawlers

---

.github/workflows/deploy.yml

Attempted fix to stop builds issued from PR's coming from Forks from failing.

Added write permission to deployment task

---

components/integrations/youtube/YouTubeFeed.tsx
components/lists/CommunityList.tsx
data/data-community-list.ts
data/markdown/pages/community/index.md
data/markdown/pages/discover/index.md
data/markdown/pages/home/index.md
data/markdown/pages/learn/index.md
data/markdown/pages/solution/devops/index.md
data/promos/mvp.ts
pages/index.tsx
pages/learn/index.tsx

Content updates

---

.github/workflows/deploy.yml

Ensured that the build GitHub action actually does run a build 😁

Added build steps to build task

---

data/markdown/pages/solution/customer-data-management/product/experience-platform/index.md
data/markdown/partials/solution/customer-data-management/web-tracking.md
data/markdown/partials/solution/personalization-testing/universal-tracker.md

Adding Universal Tracker to the web-tracking section and mentioning that default web tracking is an integrated solution
Fixes #133 
Viewed in browser

Fixes #133 - tracking content update

---

data/data-navigation.ts
data/markdown/pages/solution/commerce/product/ordercloud/index.md
data/markdown/partials/solution/commerce/ordercloud.md

Fixes #200 - small typos on the OrderCloud page
Viewed on local environment

Fixed typos on ordercloud page

---

data/markdown/pages/trials/jss-connected-demo/index.md
data/markdown/partials/solution/content-management/jss.md
data/markdown/partials/trials/jss-connected-demo/introduction.md
pages/trials/[trial]/[parent]/[child].tsx
pages/trials/[trial]/index.tsx
scripts/static-paths.ts

Introducing a jss-connected-demo introduction page.
Solves redirects that end up at /trials/jss-connected-demo and receive a 404.
Local testing

Jss trial updates

---

data/promos/newpromo.ts
pages/index.tsx

Create a new promo data file and include it on the homepage
Fixes #198 
Tested locally

Add promo on homepage for announcement

---

next.config.js

Adding missing security http headers
Based on request from IT Security in order to meet Sitecore security standards
Used the Vercel build environment to test with the online test at securityheaders.com
[Check here](https://securityheaders.com/?q=https%3A%2F%2Fdeveloper-portal-31uz3ukym-sitecoretechnicalmarketing.vercel.app%2F&followRedirects=on)

Security headers

---

data/promos/newpromo.ts

Replaced content with Hackathon announcement
Promote the upcoming hackathon
Local testing

Hackathon promo

---

.gitignore
next-env.d.ts
next-sitemap.config.js
package-lock.json
package.json

Generate a sitecore.xml and robots.txt file postbuild listing all the generated pages
Fixes #113 
Local testing and Vercel staging environment
- [Sitemap.xml](https://developer-portal-nggk5dxcs-sitecoretechnicalmarketing.vercel.app/sitemap.xml)
- [Robots.txt](https://developer-portal-nggk5dxcs-sitecoretechnicalmarketing.vercel.app/robots.txt)
_Note: base path for the sitemap paths has been set statically to developers.sitecore.com_

Generate sitemap and robots files

---

data/markdown/pages/integrations/oc-cdp/index.md
data/markdown/partials/integrations/blueprint-oc-cdp.md
data/markdown/partials/learn/integrations/cdp.md
data/markdown/partials/learn/integrations/orderCloud.md
data/markdown/partials/solution/commerce/ordercloud.md
data/markdown/partials/solution/customer-data-management/cdp.md

This PR's adds the new Sitecore OrderCloud <-> Sitecore CDP Blueprint content to the portal.

Add Sitecore OrderCloud <-> Sitecore CDP Blueprint

---

data/markdown/pages/learn/getting-started/introduction-to-composable-dxp/index.md
data/markdown/partials/learn/getting-started/articles/introduction-to-composable-dxp.md
data/markdown/partials/learn/getting-started/composable-dxp.md
data/promos/learning-essentials.ts
data/promos/videos/composable-dxp.ts
interfaces/page-info.ts
pages/404.tsx
pages/learn/getting-started/[article].tsx
pages/learn/getting-started/index.tsx
scripts/static-paths.ts

Created a new type of Getting Started article area and added a new article to cover the Introduction to Composable DXP. 
Added the following:
1. New 'Getting Started' landing page (`/learn/getting-started`) which mirrors what was done for the Integrations landing page. Lists the same partials that are shown in the Getting Started area of the `/learn` landing page.
2. Added a new Article TSX to allow for multiple Getting Started articles to be built out. Uses page info and markdown and the generic content page layout. This mirrors what was done for Integration articles.
3. Added a link on the Composable DXP partial used on the `/learn` landing page and the new Getting Started landing page to link to the article.
Fixes #241 to add doc explaining what a Composable DXP is.
Validated locally …

Issue 241 composable dxp intro

---

package-lock.json
package.json

Upgraded Next.js version
Keeping up to date
Local and [Vercel](https://developer-portal-9ssvmgi6u-sitecoretechnicalmarketing.vercel.app/)

 npm update

---

data/promos/newpromo.ts

Update promo component to SUGCON
Replacing Hackathon promo
Local and [Vercel environment](https://developer-portal-exszd0c6z-sitecoretechnicalmarketing.vercel.app/)
- [X ] I have read the Contributing guide.
- [X ] My change is a code change.

Promo SUGCON on homepage

---

data/markdown/partials/integrations/blueprint-xm-smarthub-cdp.md

Typo correction - CDB to CDP
Typo correction
N/A

Typo correction - CDB to CDP

---

components/helper/ContentPager.tsx
components/layout/GenericContentPage.tsx
interfaces/page-info.ts
pages/learn/faq/[article]/[page].tsx
pages/learn/faq/[article]/index.tsx

Adds component that allows to navigate to previous and next page in article series
Navigation improvements
Local and [Vercel](https://developer-portal-ewxip6qoc-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud)

Add article content pager

---

data/data-navigation.ts

Added events to community sub menu
Added events to community sub menu
because I can
gut feeling

Added events to community sub menu

---

data/markdown/partials/learn/faq/xm-personalize/introduction.md

Removed specific question on pricing
Removed internal question

Removed specific question on pricing

---

data/markdown/pages/learn/getting-started/xm-cloud-introduction/index.md

A new Article has been added to give an introduction on XM Cloud and how to get prepared even though it is not released.
This article gives Developers an idea on what to expect, what technologies are used and how to prepare.
I ran it locally.

Added XM Cloud Introduction Article

---

data/markdown/pages/learn/getting-started/xm-cloud-introduction/index.md

Add hero image
Open Graph support
Local and [Vercel](https://developer-portal-pkg8wcdv8-sitecoretechnicalmarketing.vercel.app)

Add heroImage to XM Cloud Introduction page

---

data/markdown/partials/learn/faq/xm-personalize/personalize-cdp.md

The document refers to "Jetstar Air Lines" but the correct name of the company is "Jetstar Airways".

Corrected reference to Jetstar Airways

---

data/faqs/cloud-portal.json
data/markdown/pages/learn/faq/cloud-portal/index.md
data/markdown/partials/learn/faq/cloud-portal/development.md
data/markdown/partials/learn/faq/cloud-portal/features.md
data/markdown/partials/learn/faq/cloud-portal/introduction.md
data/markdown/partials/learn/getting-started/composable-dxp.md
data/markdown/partials/learn/getting-started/platform-dxp-development-frameworks.md
data/markdown/partials/learn/getting-started/platform-dxp.md

External FAQ on Cloud Portal
Local and [Vercel](https://developer-portal-7dmmsb6ct-sitecoretechnicalmarketing.vercel.app/learn/faq/cloud-portal)

Cloud Portal FAQ

---

data/newsletters/2022/06.json

Adding June newsletter
Local and [Vercel](https://developer-portal-805pc9k8o-sitecoretechnicalmarketing.vercel.app/newsletter/2022/06)

Add June newsletter

---

data/markdown/pages/learn/getting-started/xm-cloud-introduction/index.md

adding the XM Cloud Playlist as well as the Headless SXA site creation video

---

data/markdown/pages/learn/getting-started/xm-cloud-introduction/index.md

Updated the Link List in xm cloud introduction article. Added 2nd video of XM Cloud Introduction and a Blogpost of Thomas Desmond.
locally

added links vor second XM Cloud intro video and Thomas Blog post

---

src/components/cards/PromoCard.tsx

Fixes #272 
Local and [Vercel](https://developer-portal-c3cktexds-sitecoretechnicalmarketing.vercel.app/newsletter)

Fix distorted banner images

---

package-lock.json
package.json
src/pages/_document.tsx

- Remove node max version
- Update minor packages

Project updates

---

public/scripts/darkMode.js
src/components/ThemeButton.tsx
src/layouts/components/head/Nav.tsx
src/pages/_document.tsx
tailwind.config.js

Add toggle to switch between light/dark mode
Local and [Vercel](https://developer-portal-j72eneljr-sitecoretechnicalmarketing.vercel.app/)

Add darkmode toggle to navbar

---

data/markdown/pages/learn/getting-started/xm-cloud-introduction/index.md

added video link about setting up XM Cloud locally using Docker
local

added video link about setting up XM Cloud locally using Docker

---

data/faqs/xm-cloud.json
data/markdown/pages/learn/faq/xm-cloud/index.md
data/markdown/partials/learn/faq/xm-cloud/customization.md
data/markdown/partials/learn/faq/xm-cloud/development.md
data/markdown/partials/learn/faq/xm-cloud/experience-edge.md
data/markdown/partials/learn/faq/xm-cloud/features.md
data/markdown/partials/learn/faq/xm-cloud/general.md
data/markdown/partials/learn/faq/xm-cloud/integration.md
data/markdown/partials/learn/faq/xm-cloud/migration.md
data/markdown/partials/learn/faq/xm-cloud/pages-components.md
data/markdown/partials/learn/faq/xm-cloud/personalization-analytics.md
data/markdown/partials/learn/faq/xm-cloud/pricing.md
data/markdown/partials/learn/faq/xm-cloud/rendering.md
data/markdown/partials/learn/faq/xm-cloud/scaling-availability.md
data/markdown/partials/learn/faq/xm-cloud/sxa.md
data/markdown/partials/learn/faq/xm-cloud/upgrades.md

XM Cloud FAQ
Local and [Vercel](https://developer-portal-i3pah0f8x-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud)

Add XM Cloud FAQ

---

data/faqs/xm-cloud.json
data/markdown/partials/learn/faq/xm-cloud/development.md
data/markdown/partials/learn/faq/xm-cloud/features.md
data/markdown/partials/learn/faq/xm-cloud/general.md

Fixing formatting, typos, grammar, and general cleanup.
Quick testing locally. Will need additional testing on Vercel preview site. Will be merging to main as this content is already live and some of the changes need to go out immediately. Changes will continue on this branch if possible.

XM Cloud FAQ fixes

---

data/markdown/partials/learn/faq/xm-cloud/customization.md
data/markdown/partials/learn/faq/xm-cloud/integration.md
data/markdown/partials/learn/faq/xm-cloud/migration.md
data/markdown/partials/learn/faq/xm-cloud/rendering.md
data/markdown/partials/learn/faq/xm-cloud/upgrades.md

Additional changes to multiple FAQ pages for formatting and updated content.
Tested locally and on Vercel preview site.

XM Cloud FAQ updates

---

data/markdown/partials/docs/commerce/discover.md
src/pages/docs.tsx

Created new partial for docs to hold Discover docs. Copied contents from Discover product page.
Fixes #323 
Tested locally and on Vercel preview site.

Added Discover docs listing to the Docs page

---

data/markdown/partials/solution/commerce/ordercloud.md
data/promos/nextjsconf.ts

Updated promos on home page and OrderCloud product page to link to the YouTube replay of Pieter's presentation.
Tested on local and on preview Vercel site.

Next js conf promo update

---

data/markdown/partials/solution/commerce/ordercloud.md
data/promos/nextjsconf.ts

Updated promos on the home page and OrderCloud product page to link to the YouTube replay of Pieter's presentation - the short video
Tested on my local

Next js conf2022 video

---

data/markdown/partials/learn/faq/cloud-portal/development.md
data/markdown/partials/learn/faq/cloud-portal/features.md
data/markdown/partials/learn/faq/cloud-portal/introduction.md

In order to support deep-linking to specific questions, the bolded questions have been updated to be headings.
Tested locally and on preview site. This is a formatting-only change.

Added heading stylings to the questions in the Cloud Portal FAQ

---

data/markdown/partials/solution/content-management/xm-cloud.md

Added the Other Learning section and a link to the Headless Frontend Development with XM Cloud blog post hosted on my personal blog. 
Tested Locally

Added a learning link to XM Cloud product page

---

data/markdown/partials/solution/content-management/xm-cloud.md

Added some blog links to the XM Cloud product page

Added xm cloud blogs

---

data/data-navigation.ts
data/markdown/pages/solution/content-management/product/content-hub-one/index.md
data/markdown/partials/solution/content-management/content-hub-one.md

Created a content hub one product page including links from navigation
This has been tested locally.

Content hub one product page

---

data/markdown/pages/learn/getting-started/introduction-to-contenthub-one/index.md
data/markdown/partials/learn/getting-started/composable-dxp.md

Content hub one introduction article

---

data/markdown/partials/solution/content-management/xm-cloud.md
data/promos/xmc-practices.ts
src/pages/index.tsx

Promotes the new XM Cloud Recommended Practices page onto the home page and the XM Cloud product page.
Fixes #361 
Tested on Vercel preview deployment and locally.

Added new promo for XM Cloud Practices on home page and XM Cloud product page

---

data/markdown/partials/solution/content-management/content-hub-one.md

The Official training section had a 'Coming Soon' link but I saw a course on learning.sitecore.com today and figured I could add a deep link to the course.
Tested on the Vercel preview site.

Adding new learning course to the page

---

data/newsletters/2022/07.json
data/newsletters/2022/08.json
data/newsletters/2022/10.json
data/newsletters/2022/11.json

Adds newsletters from July, August, October and November
Local and [Vercel](https://developer-portal-nprfz24o8-sitecoretechnicalmarketing.vercel.app/newsletter)

Add newsletters

---

data/markdown/partials/learn/faq/xm-cloud-recommended-practices/development.md

A few typos have been fixed on the [XM Cloud Development documentation page](https://developers.sitecore.com/learn/faq/xm-cloud-recommended-practices/development).

Small typos on the XM Cloud development page

---

data/markdown/pages/learn/getting-started/discover-introduction/index.md
data/markdown/partials/learn/getting-started/composable-dxp.md
data/markdown/partials/solution/commerce/discover.md

Created an article giving a developers introduction to Sitecore Discover

Introduction to sitecore discover

---

data/newsletters/2022/08.json
data/newsletters/2022/10.json
data/newsletters/2022/11.json

Fixes #370 
Local and [Vercel](https://developer-portal-dwv71fnr7-sitecoretechnicalmarketing.vercel.app/newsletter/2022/11)

Fixes newsletter links not working #370

---

data/markdown/partials/solution/content-management/xm-cloud.md

Updated URL for XM Cloud Headless SXA Starter Template repo

Updated Headless SXA Starter repo URL

---

data/markdown/partials/docs/integrations/connect.md
data/markdown/partials/solution/integrations/connect.md
src/pages/docs.tsx

Adding the new Sitecore Connect documentation based on issue #379.  This is only a documentation update.
This was tested locally during development.

Added Documentation for Connect

---

src/components/common/MarkdownContent.tsx
src/styles/buttons.css

Add dark:prose-invert class to articles to fix text color
Local

Fix dark mode text color

---

data/markdown/partials/learn/starter-kits/xm-cloud.md
data/markdown/partials/solution/content-management/xm-cloud.md

Updated URL's for XM Cloud Foundation Head repository, and associated link naming.

Updated xmc foundation head repo URL

---

src/components/cards/Article.tsx
src/components/cards/Cards.styles.css
src/components/cards/LinkItem.tsx
src/components/cards/Repository.tsx
src/styles/global.css

Minor visual improvements (some padding), but more efficient written in css
Local

Style improvements to cards on product pages

---

src/components/common/Row.tsx
src/components/common/TextLink.tsx
src/components/sidebar-nav/SidebarNav.styles.css
src/components/sidebar-nav/SidebarNav.tsx
src/layouts/GenericContentPage.tsx

PR changes the way how the secondary navigation is shown on mobile.
Local and [Vercel](https://developer-portal-robearlam-sitecoretechnicalmarketing.vercel.app/content-management/xm-cloud)

Show InPageNav as dropdown on mobile

---

src/common/translate-date.ts

Fixes an hydration error when the user OS has a different locale.
Local and Vercel environment

fix hydration error

---

apps/devportal/data/markdown/pages/learn/getting-started/migrating-to-the-sitecore-composable-dxp/index.md

Added a new article to the list at the top of the DXP Migration page to link to the XP Marketing Automation scenario.
Tested locally using npm run dev.

Adding XP Marketing Automation article to migration page

---

apps/devportal/data/data-navigation.ts
apps/devportal/data/markdown/partials/solution/customer-data-management/cdp.md
apps/devportal/data/markdown/partials/solution/personalization-testing/personalize.md

This contains the new CDP/Personalize docs, links to learning, plus added links to the cloud portal since that's now the case.  Now all customers are on it but it will become increasingly likely over the next few months.  These changes are all docs updates.
Tested the changes locally

Cdp personalize updates

---

apps/devportal/data/markdown/partials/solution/commerce/discover.md

Added a reference to the StoryBook docs for Sitecore Discover product page

Added reference to Discover Storybook

---

apps/devportal/data/markdown/pages/solution/commerce/product/discover/index.md

Added link to YouTube Playlist for Sitecore Discover
Closes #428

Added YouTube Playlist to Discover Product Page

---

packages/ui/components/cards/Cards.styles.css
packages/ui/components/cards/LinkItem.tsx

issue 433 - renamed link to text-link

---

packages/ui/components/common/ContentPager.tsx
packages/ui/styles/buttons.css

Closes #427 
Local and [Vercel](https://developer-portal-lgwdmunwl-sitecoretechnicalmarketing.vercel.app/learn/faq/xm-cloud/personalization-analytics)

Apply grid and style to back-forward paging

---

packages/sc-changelog/lib/search.ts

This PR fixes an issue for loading single entry pages using the release date restriction
Local

fix release date

---

apps/devportal/package.json
apps/devportal/public/scripts/darkMode.js
apps/devportal/src/pages/_app.tsx
apps/devportal/src/pages/_document.tsx
package-lock.json
packages/ui/layouts/components/header/ThemeButton.tsx

Use next-themes package to manage dark mode integration instead of custom implementation
Local

Use next-themes for dark-mode

---

apps/devportal/src/pages/api/changelog/v1/indexing.ts

This PR adds pagination to the indexing endpoint.
Each requests has a property hasMore and and a propery endCursor. By default the endpoint shows 10 results per page. When you want to request the next page the request needs to include the endCorsor value as "cursor" parameter value.
First request would be to `/api/changelog/v1/indexing`
this will results in the response:
```
{
"total": 64,
"hasMore": true,
"endCursor": "eyJzZWFyY2hBZnRlciI6WzE2ODA4ODMyMDAwMDAsIm9sSTJtdHhMM2stZFdWOUx1VkpGdEEiXSwiY291bnQiOjIwfQ==",
"entries": []
}
```
The request for page 2 would be: `/api/changelog/v1/indexing?cursor=[value of endCursor from request 1]`
To indicate whether we reached the final page the property "hasMore" will return false
_Note: Page size defaults to 10, but can be customed using `size` …

Add pagination to indexing endpoint

---

apps/devportal/data/markdown/partials/solution/content-management/edge-xm.md

Some good content, especially by John Rappel, on Experience Edge which is applicable to current XM Cloud folks. Added a new section for "Community Articles" and added some links, with a credit to the author.
On Vercel and Markdown preview on GitHub

Added community articles for Edge

---

apps/devportal/src/pages/changelog/[product]/index.tsx

Update to title and description on product page to use specific product name and description
Local

Update to title and description on product page

---

apps/devportal/data/markdown/partials/solution/content-management/edge-xm.md

A new article by John Rappel: https://sitecorerap.wordpress.com/2023/06/16/leveraging-experience-edge-webhooks-for-high-quality-sitecore-implementations/
Added to the Edge page.
Tested on Vercel preview site.

Add new John Rappel article

---

apps/devportal/src/components/integrations/sitecore-search/PreviewSearchInput.tsx
packages/tailwind-config/tailwind.config.js

Resolves #491 by setting min-height for preview search

Issue 491; set min-height for preview search

---

apps/devportal/src/pages/changelog/[product]/[entry].tsx

Remove 'empty' description (OpenGraph) for entry pages
Local

Fix description for OG

---

apps/devportal/package.json
apps/devportal/src/pages/_app.tsx
package-lock.json

This PR adds a loading indicator at the top of the page to indicate that the page is loading
Local and [Vercel](https://developer-portal-git-feature-92da98-sitecoretechnicalmarketing.vercel.app/)

Implemented loading indicator for pages

---

packages/ui/styles/_utilities.css

Adjust text color for accessibility 
Local

change text color in light mode to blackAlpha

---

apps/devportal/data/markdown/pages/solution/content-management/product/search/index.md

Added metadata for youtube playlist to display recent Search videos on the Search page.
On Vercel preview site.

Adding YouTube playlist to Search page

---

apps/devportal/data/markdown/partials/solution/devops/containers.md

Added some good LinkedIn posts to the Containers page

Added k8s community content

---

apps/devportal/data/markdown/partials/learn/faq/xm-cloud/development.md

Fix markdown for section headings

---

apps/devportal/data/markdown/partials/solution/content-management/search.md

Added example repo links to Sitecore Search product page

Sitecore Search - Updated Product Page

---

apps/devportal/package.json
apps/devportal/src/components/integrations/sitecore-search/PreviewSearchInput.tsx
apps/devportal/src/components/integrations/sitecore-search/SearchResults.tsx
apps/devportal/src/pages/_app.tsx
apps/devportal/src/pages/search.tsx
package-lock.json

Version 2 of the Search SDK has been release. This was a major version change and involved breaking changes that needed to be implemented.

Upgrade Search SDK to v2

---

apps/devportal/src/pages/changelog/current.tsx

Remove links to old CDP/Personalize changelog

Remove CDP and Personalize

---

apps/devportal/package.json
package-lock.json

Upgraded Sitecore Search SDK to v2.0.0 from v2 alpha release.

Upgraded Search SDK to v2

---

apps/devportal/data/markdown/partials/solution/commerce/ordercloud.md

Need to highlight self-exploration for developers early when learning. Fixes #530 . 
Texted on Vercel preview site.

Move Try it Yourself to the top

---

apps/devportal/data/markdown/pages/learn/getting-started/migrating-to-the-sitecore-composable-dxp/index.md

As part of the migration adventure, we have added some community articles to our collection. These are now added to our migration landing page with this PR.
I also updated the references to jasonstcyr.com with the community.sitecore.com equivalents, to match with the articles in the migration adventure.
Tested locally and on Vercel preview site.

Adding additional migration guide articles

---

apps/devportal/data/markdown/partials/solution/content-management/xm-cloud.md

For XM Cloud product page, adding a community article about using wildcards that was co-developed with Richard Seal
On Vercel preview site.

Add wildcard blog article

---

apps/devportal/data/markdown/pages/commerce/ordercloud.md

This PR fixes image alignment on the OrderCloud page
Local

fix image alignment

---

apps/devportal/src/components/navigation/ChildNavigation.tsx
packages/ui/components/common/Hero.tsx

Fixes issue with flickering hero banner when loading page
Child menu load defaults to normal instead of mobile
Local

Prevent nav flickering

---

apps/devportal/data/markdown/pages/contribute/components.md
apps/devportal/data/markdown/pages/contribute/configuration.md
apps/devportal/data/markdown/pages/contribute/page-structure.md
packages/ui/components/promos/videoPromo/videoPromo.tsx

- Updates to documentation
- Added Chakra components to videoPromo
Local

Update components and configuration documentation

---

apps/devportal/data/markdown/pages/trials/index.md

In order to support the Netlify virtual booth, doing a slight refresh on the developers.sitecore.com/trials page to highlight the three trials that are available.
Tested locally in light mode and dark mode.

Trials netlify refresh

---

apps/devportal/src/components/changelog/ChangeLogItem.tsx
apps/devportal/src/lib/theme/proseTheme.ts

This PR changes code highlighting in rich text
Local van [Vercel](https://developer-portal-83y6r1dtf-sitecoretechnicalmarketing.vercel.app/changelog)

Code formatting in prose text

---

apps/devportal/src/components/changelog/ChangelogFilter.tsx
apps/devportal/src/components/changelog/Hint.tsx
apps/devportal/src/lib/changelog/changelog.ts
package-lock.json
packages/ui/components/dropdown/MultiSelect.tsx
packages/ui/package.json

This PR adds a Chakra wrapper for the react-select component and therefore enables blok styling to the component
Also fixes dark mode issue with the dropdown text

Add chakra-react-select wrapper

---

packages/ui/components/dropdown/MultiSelect.tsx

Align styling of react-select component with Blok
Local

react-select - align with blok styling

---

apps/devportal/src/components/changelog/ChangeLogItem.tsx

This PR adjusts the width of the image requested from CH ONE
Local

adjusted with of image request

---

apps/devportal/src/components/changelog/ChangelogItemMeta.tsx

Align label colors with Blok
Local

Align changetype label color with Blok

---

apps/devportal/data/newsletters/2023/08.json
apps/devportal/data/newsletters/2023/09.json
apps/devportal/data/newsletters/2023/10.json

Catching the newsletter archive up with the latest newsletters from August, September, and October 2023.
Tested locally and on Vercel. Tested scenarios:
1. "Latest" URL: /newsletter/latest
2. Direct URLs: 
- /newsletter/2023/08
- /newsletter/2023/09
- /newsletter/2023/10
4. Navigation between months
5. Listing on /newsletter shows new publications

FY23 Q1 newsletters

---

apps/devportal/src/pages/changelog/[product]/index.tsx
apps/devportal/src/pages/changelog/current.tsx
apps/devportal/src/pages/changelog/index.tsx

Fixes #571
Fixes #572
Local and [Vercel](https://developer-portal-git-issue-cu-66e423-sitecoretechnicalmarketing.vercel.app/changelog/current)

Update Changelog current page

---

apps/devportal/next.config.js

Fixes #564 
Local and [Vercel](https://developer-portal-git-issue-56-8f4ac8-sitecoretechnicalmarketing.vercel.app/trial)

Add trial-trials redirect

---

apps/devportal/data/markdown/pages/learn/faq/xm-cloud/customization.md

The current FAQ question around custom identity providers was out of date. We now have SSO support. The text has been updated to reflect this and link to the SSO documentation.
Tested locally.

Update sso faq question

---

packages/ui/components/integrations/stackexchange/StackExchangeFeed.tsx

Fix key prop warning in StackExchange component
Local

Fix key prop warning

---

apps/devportal/data/markdown/pages/trials/jss-connected-demo/manifest.json
apps/devportal/src/components/navigation/ChildNavigation.tsx
apps/devportal/src/components/navigation/DropDownMenu.tsx
apps/devportal/src/layouts/Sidebar.tsx
apps/devportal/src/lib/interfaces/page-info.ts
packages/ui/lib/utils/stringUtil.ts

Sidebar menu supports sections and mobile

---

apps/devportal/src/components/navigation/ChildNavigation.tsx
apps/devportal/src/components/navigation/DropDownMenu.tsx
apps/devportal/src/layouts/Sidebar.tsx

This PR fixes some semantic html issues
Local

Use semantic html for sidebar nav

---

apps/devportal/src/components/navigation/NavBar.tsx
apps/devportal/src/pages/_app.tsx
apps/devportal/src/pages/search.tsx

This PR adds a check for Sitecore Search environment variables. When none found search is disabled
Local

Check for search env variables

---

apps/devportal/src/components/markdown/MarkdownContent.tsx
apps/devportal/src/components/navigation/ChildNavigation.tsx
apps/devportal/src/components/navigation/Footer.tsx
apps/devportal/src/layouts/Sidebar.tsx
apps/devportal/src/lib/theme/proseTheme.ts
apps/devportal/src/pages/_app.tsx
packages/ui/components/cards/Download.tsx
packages/ui/components/cards/Group.tsx
packages/ui/components/helpers/CenteredContent.tsx
packages/ui/components/links/ButtonLink.tsx

This PR adds improvements to the markup generated from the markdown sources
Adds fix for the footer overflowing onto child navigation 

Markdown improvements

---

apps/devportal/src/components/navigation/InPageNavSmall.tsx
apps/devportal/src/components/navigation/NavBar.tsx
apps/devportal/src/layouts/ArticlePage.tsx
apps/devportal/src/layouts/ChildOverviewPage.tsx
apps/devportal/src/layouts/DefaultContentPage.tsx
apps/devportal/src/layouts/GenericContentPage.tsx
apps/devportal/src/layouts/Sidebar.tsx
apps/devportal/src/layouts/ThreeColumnLayout.tsx

This PR adds InPageNav support for smaller screens by making use of the Chakra Menu component

InPageNav support for smaller screens

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/appendix-i/xm-cloud-glossary.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/index.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/troubleshooting-docker.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/external-data-integration/index.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/index.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/information-architecture/index.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/search.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/sitemap.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/index.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-experience/branching-strategy.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/discovery.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/information-architecture.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-planning.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/security/head-application-security.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/security/index.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/devops.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/index.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/project-solution-setup.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/setup-content-serialization.md
apps/devportal/src/components/common/contribute.tsx
apps/devportal/src/layouts/ArticlePage.tsx
apps/devportal/src/lib/interfaces/page-info.ts
apps/devportal/src/lib/page-info.ts

Adding a new section to the bottom of each recipe page to help with contributions to the Accelerate program.

Add message on how to contribute to each recipe page

---

apps/devportal/data/markdown/pages/contribute/index.md

Adds link to  repository to the contribution guide
Local

Add link to GH repo

---

.github/workflows/checklinks.yml
.github/workflows/markdown-links.config.json

Adds GH action to check links in markdown files

Add action to check markdown links

---

apps/devportal/data/markdown/pages/learn/faq/xm-cloud-recommended-practices/deployment.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud-recommended-practices/development.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud-recommended-practices/getting-started.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud-recommended-practices/index.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud-recommended-practices/preparing-for-project.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud-recommended-practices/project-structure.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/customization.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/development.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/experience-edge.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/features.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/index.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/integration.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/migration.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/pages-components.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/personalization-analytics.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/pricing.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/rendering.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/scaling-availability.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/sxa.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/upgrades.md

This PR adds a info message to the XM Cloud FAQ and XM Cloud Recommended practices point to the accelerate docs
Local and [Vercel](https://developer-portal-git-content-717c5b-sitecoretechnicalmarketing.vercel.app/)

Add alert message pointing to accelerate

---

apps/devportal/package.json
apps/devportal/src/pages/api/og.tsx
package-lock.json

Downgrade Next.js to 13.5.6 due to issue with serverless functions

downgrade to 13.5.6

---

apps/devportal/data/newsletters/2023/12.json
apps/devportal/data/newsletters/2024/01.json
apps/devportal/src/components/newsletter/NewsletterStory.tsx
apps/devportal/src/lib/newsletter.ts
apps/devportal/src/pages/newsletter/[year]/[month].tsx
apps/devportal/src/pages/newsletter/[year]/index.tsx
apps/devportal/src/pages/newsletter/index.tsx

This PR adds the newsletters for December and January
Refactored data retrieval

Add newsletters December and January

---

apps/devportal/src/components/navigation/ChildNavigation.tsx

Use NextLink instead of Chakra UI link component
Fixes #629 

fix darkmode flickering on load

---

apps/devportal/src/components/sitecore-search/PreviewSearchInput.tsx

Fixes #611 
- [X ] Bug fix (non-breaking change which fixes an issue)

add background to searchresults when 0 suggestions

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/creating-new-components.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/devops.md

Add new devops recipe to the Accelerate pages

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/project-solution-setup.md

Updated the recipe to include Azure DevOps as a supported git provider.
n/a

Update the recipe now that XMC supports Azure DevOps

---

apps/devportal/data/newsletters/2024/02.json
apps/devportal/src/components/navigation/SidebarNavigation.tsx
apps/devportal/src/components/newsletter/NewsletterNav.tsx
apps/devportal/src/components/newsletter/NewsletterStory.tsx
apps/devportal/src/pages/newsletter/[year]/[month].tsx

This PR adds the Feb 24 newsletter as well as some minor functionality updates:
- Use SidebarNavigation component instead of custom navigation
- Reponsive design improvements

Add February '24 newsletter

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/creating-a-site.md

Fixing some typos and grammar errors.

Fix typos and grammatical errors

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-experience/branching-strategy.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/migration.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/personalize-cdp.md
apps/devportal/data/markdown/pages/learn/getting-started/managed-cloud-with-containers/index.md
apps/devportal/data/markdown/pages/learn/integrations/send-oc.md

In reading the documentation, I stumbled upon a typo:
https://developers.sitecore.com/learn/accelerate/xm-cloud/pre-development/developer-experience/branching-strategy#branching-strategy
Having forked and cloned the repo locally, I resolved the typo I spotted, then searched for additional typos within the repository and made necessary adjustments.  Six typos have been addressed; only Markdown files have been modified.  
These are non-breaking documentation updates to address misspellings only.

Addressing typos throughout devportal docs

---

apps/devportal/data/markdown/pages/learn/getting-started/next-js/index.md

Fix twitter hashtag and add additional Next.js resource

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/creating-a-component-gallery.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json

[Link to page on preview deployment](https://developer-portal-git-fork-crh-83d00b-sitecoretechnicalmarketing.vercel.app/learn/accelerate/xm-cloud/implementation/developer-experience/creating-a-component-gallery)

Add "Create a component gallery" page to xmc accelerate docs

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-experience/dev-workflow-codespaces.md

Updated the recipe to include updates for JSS 21.6

Update recipe with JSS 21.6 details

---

apps/devportal/src/components/navigation/NavBar.tsx
apps/devportal/src/components/navigation/SearchButton.tsx
apps/devportal/src/components/sitecore-search/PreviewSearchInput.tsx
apps/devportal/src/components/sitecore-search/SearchInputSwitcher.tsx

Rewrite of the preview search component to leverage the latest SDK updates and fix responsive issues
Local and [Vercel](https://developer-portal-git-feature-ed7d42-sitecoretechnicalmarketing.vercel.app/)

Update preview search component

---

apps/devportal/src/pages/changelog/[product]/index.tsx

Fix link to product rss feeds

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-planning/preparing-for-an-xm-cloud-project.md

Link to preview: https://developer-portal-git-fork-max-eae296-sitecoretechnicalmarketing.vercel.app/learn/accelerate/xm-cloud/pre-development/project-planning/preparing-for-an-xm-cloud-project

Adds "Preparing for an XM Cloud Project" page to Accelerate documents

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/appendix-ii/example-code/template-module-json.md

Fix typo and rule order

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/appendix-ii/example-code/template-module-json.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json

[Link to deployed page](https://developer-portal-git-fork-crh-abf9ad-sitecoretechnicalmarketing.vercel.app/learn/accelerate/xm-cloud/appendix-ii/example-code/template-module-json)

ACC-76 Updates "template.module.json" guide

---

apps/devportal/src/components/common/Meta.tsx
apps/devportal/src/layouts/Layout.tsx
packages/ui/components/integrations/engage/EngageTracker.tsx

This PR fixes the OG meta tags by removing the loading condition in the EngageTracker

Fix OG meta tags

---

apps/devportal/src/components/changelog/ChangelogEntries.tsx
apps/devportal/src/components/navigation/NavBar.tsx
apps/devportal/src/components/navigation/SearchButton.tsx
apps/devportal/src/components/navigation/SidebarNavigation.tsx
apps/devportal/src/components/newsletter/NewsletterNav.tsx
apps/devportal/src/components/sitecore-search/PreviewSearchInput.tsx

This PR introduces a resize of the top searchbar on focus

resize search topbar on focus

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/final-steps/go-live-checklist.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json

Link to preview: https://developer-portal-git-fork-max-6f1ca7-sitecoretechnicalmarketing.vercel.app/

Adds "Go-Live Checklist" page to Accelerate documents

---

apps/devportal/data/newsletters/2024/03.json

Add March newsletter

---

apps/devportal/src/components/changelog/ChangelogItemMeta.tsx

Fixes #680 - using the same UX as the homepage list
Local

Use popover for multiple tagged products

---

apps/devportal/src/components/changelog/ChangelogEntries.tsx
apps/devportal/src/components/changelog/ChangelogItemMeta.tsx

Fixes incorrect product icon bug #684 
Local

Fix product icon error in popover

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/redirect.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json

Added Redirect recipe for sitecore accelerate.
the recipe is about handling redirects using SXA and it discusses how to handle different requirements, for example when you have a large number of redirects after migrating to xmcloud.
There is no code changes, and the documentation page is tested localy.
- [X ] Documentation update (non-breaking change; modified files are limited to the `/data` directory or other markdown files)
- [X ] I have read the Contributing guide.

Adding redirect documentation for accelerate

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/redirect.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json

* Adding redirect documentation for accelerate
* - Adjust wording for redirect recipe
- Restructure the documentation for redirect recipe
- Adding references for Netlify
* Changing related documentation format to use link
* Changing the sample code to use middleware plugin

Adding this back in: Adding redirect documentation for accelerate (#675)

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/information-architecture/content-audit.md
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/information-architecture/index.md

Link to Preview: https://developer-portal-git-fork-max-443979-sitecoretechnicalmarketing.vercel.app/

Adds "Content Audit" page to Accelerate documents

---

apps/devportal/data/data-navigation.ts

Fix SIF url in data-navigation

---

README.md
apps/devportal/data/markdown/pages/commerce/experience-commerce.md
apps/devportal/data/markdown/pages/content-management/headless.md
apps/devportal/data/markdown/pages/content-management/sxa.md
apps/devportal/data/markdown/pages/contribute/configuration.md
apps/devportal/data/markdown/pages/contribute/index.md
apps/devportal/data/markdown/pages/devops/developer-collection.md
apps/devportal/data/markdown/pages/marketing-automation/experience-platform.md
apps/devportal/data/markdown/partials/solution/customer-data-management/reference-data-service.md

Fix CLI download url in developer-collection

---

apps/devportal/data/markdown/pages/downloads/Team_Development_for_Sitecore/6x/Team_Development_for_Sitecore_604/Release_Notes.md
apps/devportal/data/markdown/pages/downloads/Team_Development_for_Sitecore/6x/Team_Development_for_Sitecore_604/index.md
apps/devportal/data/markdown/pages/downloads/Team_Development_for_Sitecore/index.md

Sitecore TDS 6.0.4

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/manifest.json
apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-architecture/rate-limits-and-caching.md

Add in the Rate Limits and Caching recipe
New recipe: https://developer-portal-git-recipe-r-de6dbc-sitecoretechnicalmarketing.vercel.app/learn/accelerate/xm-cloud/pre-development/project-architecture/rate-limits-and-caching

Add rate limits and caching recipe to the site

---

apps/devportal/data/markdown/pages/downloads/Team_Development_for_Sitecore/6x/Team_Development_for_Sitecore_602/Release_Notes.md
apps/devportal/data/markdown/pages/downloads/Team_Development_for_Sitecore/6x/Team_Development_for_Sitecore_603/Release_Notes.md
apps/devportal/data/markdown/pages/downloads/Team_Development_for_Sitecore/6x/Team_Development_for_Sitecore_604/Release_Notes.md

Fixed the typo in TDS release notes, changed `Sitecore for Visual Studio` to `Team Development for Sitecore`
Local

Fix typo in TDS release notes

---

apps/devportal/data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70330/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Identity/index.md

Adds Sitecore Identity 7.0.330
Local

Add sitecore identity 7.0.330

---

apps/devportal/data/markdown/pages/learn/faq/xm-cloud/development.md
apps/devportal/data/markdown/pages/learn/faq/xm-cloud/features.md

Update to the FAQ to remove 2022 SYM reference and direct users to more current migration options.
Fixes #681
Local and on Vercel preview

Updating XM Cloud FAQ development section around migration-related questions

---

apps/devportal/data/markdown/pages/downloads/index.md

Update Sitecore Identity latest version link reference to 7.0.330
Local

Fix link reference to Sitecore Identity latest version

---

apps/devportal/data/markdown/pages/downloads/Active_Directory/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Connect_for_Microsoft_Dynamics_365_Commerce/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_IP_Geolocation_Service_Client/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Plugin_for_Stylelabs_DAM/index.md

Removing extra backslash character in `Active Directory` `Microsoft Dynamics 365 Commerce` `Sitecore IP Geolocation Service Client` `Sitecore Connect™ for Sitecore DAM` download page
Local

Removing extra character in download page

---

apps/devportal/data/markdown/pages/downloads/Sitecore_Azure_Blob_Storage/1x/Sitecore_Azure_Blob_Storage_Az_Migration_Script/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Azure_Blob_Storage/index.md

Add Sitecore Azure Blob Storage Az Migration Script
Local

Add Sitecore Azure Blob Storage Az Migration Script

---

apps/devportal/data/markdown/pages/downloads/Sitecore_Headless_Rendering/22x/Sitecore_Headless_Rendering_2200/Release_Notes.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Headless_Rendering/22x/Sitecore_Headless_Rendering_2200/index.md

Headless 22 Release

---

apps/devportal/src/lib/page-info.ts

The `Edit this page on GitHub` links on non-index pages are incorrect, and show a 404 in Github.
Local

Fix edit link bug

---

apps/devportal/src/pages/changelog/current.tsx

Fix links for current release notes. `/changelog/current`
Local

Fix links for current release notes

---

apps/devportal/src/pages/404.tsx
apps/devportal/src/pages/500.tsx

Add Blok styling to error pages
Local

Update error pages

---

apps/devportal/data/markdown/pages/downloads/xm-cloud/index.md

Addresses request from #770 
Local and on [Vercel preview](https://developer-portal-o12bnnx6d-sitecoretechnicalmarketing.vercel.app/downloads/xm-cloud#xm-to-xm-cloud-content-migration-tool).

Adding note for future version.

---

apps/devportal/data/markdown/pages/learn/faq/xm-personalize/customization.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/development.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/edge-serverless.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/features.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/index.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/managed-cloud.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/manifest.json
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/personalize-cdp.md
apps/devportal/data/markdown/pages/learn/faq/xm-personalize/scaling.md

This PR addresses the following feedback from @thomas-desmond :
* Referring to Experience Edge as simply Edge is too vague. Edge, especially in the front-end world, can refer to too many things. I would recommend, at least for the title, calling out Experience Edge explicitly. So, the page title would be "Experience Edge & Serverless Hosting". 
* I'm not sure how generic you want to be with Serverless providers, but it's probably worth adding a bullet for the fact that Sitecore is officially partnered with Netlify & Vercel.
* I'm all about specifics, so I'd want the question to be: Why choose serverless hosts like Vercel/Netlify for Sitecore XM?
* The last bullet on webhooks/cli you could add they offer Continuous Integration and Continuous Delivery (CI/CD) features as well 
* "Severless" …

Update Edge/Serverless section of XM+Personalize FAQ

---

apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud/tutorials/create-a-component.md
apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud/tutorials/create-a-site.md
apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud/tutorials/setup-xm-cloud.md

Addressing initial feedback from MVP review of XM Cloud tutorials.
Fixes #784 
Local and [on Vercel](https://developer-portal-git-xm-cloud-83f36c-sitecoretechnicalmarketing.vercel.app/learn/getting-started/xm-cloud/tutorials).

XM Cloud Tutorial MVP feedback

---

apps/devportal/data/markdown/pages/learn/getting-started/xm-cloud-introduction/index.md
apps/devportal/data/markdown/partials/learn/getting-started/xm-cloud.md
apps/devportal/data/markdown/partials/solution/content-management/xm-cloud.md

add links to the new XM Cloud Tutorial series in 3 places.

---

apps/devportal/data/data-navigation.ts

Fix incorrect logo for Managed Cloud in Products Navigation.
Local

Fix incorrect logo for ManagedCloud

---

apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104/index.md

- Update SXP 10.4 downloads page with link to SCSE module
- Update target dates for forthcoming modules
- Tested on localhost:3000

Update SXP10.4 page with link to SCSE, update forecast dates

---

apps/devportal/data/markdown/pages/devops/sitecore-install-framework.md

Fix broken link reference for SIF.
Local

Fix link reference for SIF

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-architecture/rate-limits-and-caching.md

Update the recipe to include more caching options to tune

Update the recipe to include more caching options to tune

---

apps/devportal/data/markdown/pages/learn/faq/xm-personalize/development.md

Fix broken link reference for `SSR proxy`
Local

Fix broken link reference

---

apps/devportal/data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70331/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Identity/index.md

Added Identity Server 70331 release

Added Identity Server 70331 release

---

apps/devportal/data/markdown/pages/learn/faq/xm-cloud/customization.md

Clarify the official position on deploying customizations to the XMC Platform

---

apps/devportal/data/markdown/pages/commerce/experience-commerce.md

Updates link to the XC user documentation site and replaces version specific URL with the 'latest' version.
Local

Replace version specific with latest in XC

---

apps/devportal/data/data-navigation.ts

Remove legacy Sitecore Downloads link `dev.sitecore.net` from the top right of the header.
Local

Remove legacy Sitecore Downloads link

---

apps/devportal/data/markdown/pages/content-management/edge-content-hub.md
apps/devportal/data/markdown/partials/solution/content-management/edge.md

Fix broken link reference in Experience Edge
Local

Fix broken link reference in XE

---

apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/information-architecture/wildcard-pages.md

Fix the dynamic routes in "Wildcard Pages" page.
Local

Fix the dynamic routes in "Wildcard Pages" page

---

apps/devportal/data/markdown/pages/docs.md

Removing extra url in docs page.
Local

Removing extra url in docs page

---

apps/devportal/data/markdown/pages/community.md

Fixed broken imageSource in community page.
Local

Fixed broken imageSource in community page

---

apps/devportal/data/data-navigation.ts

Fixed navigation for Documentation.
Local

Fixed navigation for Documentation

---

apps/devportal/data/data-navigation.ts

Removed duplicate Content Hub item from Product Nav menu/
Closes #850

Removed duplicate product from Nav

---

apps/devportal/data/markdown/pages/downloads/Data_Exchange_Framework/9x/Data_Exchange_Framework_900/index.md
apps/devportal/data/markdown/pages/downloads/Dynamics_CRM_Connect/9x/Sitecore_Connect_for_Microsoft_Dynamics_365_for_Sales_900/index.md
apps/devportal/data/markdown/pages/downloads/Salesforce_Connect/9x/Sitecore_Connect_for_Salesforce_CRM_900/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Connect_for_Content_Hub/5x/Sitecore_Connect_for_Content_Hub_520/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Connect_software_for_Salesforce_Marketing_Cloud/1x/Sitecore_Connect_software_for_Salesforce_Marketing_Cloud_90/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104/Release_Notes.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104/index.md

- Updated documentation on SXP 10.4 and connector modules download pages. 
- Tested on localhost 3000

Update SXP10.4 and connector modules documentation

---

apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service/5x/Sitecore_Publishing_Service_500/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service/6x/Sitecore_Publishing_Service_600/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service/7x/Sitecore_Publishing_Service_7020/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1000/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1010/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1020/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1030/index.md
apps/devportal/data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1040/index.md

- Updated compatibility information on recent version pages of Sitecore Publishing Service and Sitecore Publishing Service Module.
- Tested on localhost/3000

SPS & SPS Module - updated compatibility info

---

apps/devportal/data/markdown/pages/downloads/Sitecore_CLI/index.md

Add CLI download url for 6.0.18
Local

Add CLI download url for 6.0.18

---

data/markdown/pages/downloads/index.md

Update downloads link

---

src/components/markdown/contribute.tsx
src/lib/page-info.ts

Fixed GitHub edit link.
Local.

Fixed GitHub edit link

---

data/markdown/pages/contribute/configuration.md
data/markdown/pages/contribute/content.md
data/markdown/pages/contribute/page-structure.md

Fixed link references in contribute.
Local

Fixed link references in contribute

---

README.md

Fixed broken link for logo image.
Local

Fixed broken link for logo image

---

src/components/markdown/contribute.tsx

Fixed GitHub issue link.
Local.

Fixed GitHub issue link

---

data/markdown/pages/articles/2024/09/xmcloud-sites-release-september.md
data/markdown/pages/products/xm-cloud/index.md

added XM Cloud Sites Release article

---

data/markdown/pages/articles/2024/09/xmcloud-sites-release-september.md

Removing extra words

---

data/markdown/pages/learn/accelerate/xm-cloud/manifest.json
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-experience/nextjs-app-router-preparation.md

https://sitecore.atlassian.net/browse/ACC-5

Added app router recipe.

---

data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-experience/hosting-web-application.md

Added Hosting Web Application recipe.
https://sitecore.atlassian.net/browse/ACC-135

Added Hosting Web Application recipe

---

data/markdown/pages/learn/accelerate/xm-cloud/manifest.json

Adding entry to manifest.json for Hosting web Application

Adding entry to manifest.json for Hosting web Application

---

data/markdown/pages/products/discover/index.md

Fixed broken link reference in /products/discover.
Local.

Fixed broken link reference in /products/discover

---

data/markdown/pages/products/ordercloud/index.md

Fixed broken link reference for Ordercloud Feature Guide.
Local.

Fixed broken link reference for Ordercloud Feature Guide

---

data/markdown/pages/learn/accelerate/xm-cloud/implementation/external-data-integration/getting-component-specific-data.md

https://sitecore.atlassian.net/wiki/spaces/FM1/pages/4459168071/Getting+Component+Specific+Data

Updated markdown as per recipe.

---

data/markdown/pages/learn/accelerate/xm-cloud/manifest.json
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-planning/xm-xp-to-xmc.md

Updated recipe title and nav title.

---

data/markdown/pages/learn/accelerate/xm-cloud/implementation/external-data-integration/custom-editing-ux-3rd-party-integrations.md
data/markdown/pages/learn/accelerate/xm-cloud/implementation/information-architecture/workflow.md

Fixed broken link references in 3rd party doc.
Local.

Fixed broken link references in 3rd party doc

---

data/markdown/pages/downloads/Sitecore_CLI/6x/Sitecore_CLI_6023/Release_Notes.md
data/markdown/pages/downloads/Sitecore_CLI/6x/Sitecore_CLI_6023/index.md
data/markdown/pages/downloads/Sitecore_CLI/index.md
data/markdown/pages/downloads/index.md

Release notes for Sitecore CLI 6.0.23

Devex 3827 cli 6023 release notes

---

data/markdown/pages/learn/accelerate/xm-cloud/pre-development/discovery/moving-to-saas.md

Spell check, link check, moved some content around.

---

data/markdown/pages/learn/accelerate/index.md
data/markdown/pages/learn/accelerate/xm-cloud/index.md
data/markdown/pages/learn/accelerate/xm-cloud/manifest.json
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-planning/index.md

Reorg of landing pages to remove references to XMC

---

data/gql/codegen.ts
package.json
src/gql/generated/gql.ts
src/gql/generated/graphql.ts
src/gql/generated/index.ts
src/lib/changelog/changelog.ts

This PR fixes preview mode for the changelog
Local

Fix changelog preview 

---

data/markdown/pages/learn/accelerate/xm-cloud/index.md

Fixed typo in `/learn/accelerate/xm-cloud`.
Local.

Fixed typo in /learn/accelerate/xm-cloud

---

data/markdown/pages/learn.md

Fixed broken link reference in `/learn`.
Local.

Fixed broken link reference in /learn

---

src/lib/utils/stringUtil.ts

This PR fixes forward slash error in changelog URLs
fixes #922 

Fix forward slash error in changelog URLs

---

data/markdown/pages/learn/faq/xm-personalize/personalize-cdp.md

fix broken link

---

data/markdown/pages/downloads/Sitecore_Headless_Rendering/22x/Sitecore_Headless_Rendering_2200/Release_Notes.md

DEVEX-3707 Update release notes

---

data/markdown/pages/learn/accelerate/content-hub/pre-development/sprint-zero/multi-environments-deployment.md

Broken links fixes

---

src/lib/changelog/changelog.ts
src/lib/changelog/common/changelog.ts

This PR fixes an issue in preview mode when no filters are used.
Local, Test, Staging and Preview

Fix changelog issues in preview mode

---

data/markdown/pages/learn/accelerate/xm-cloud/implementation/sitecore-search.md

Removal of limits specific to contracts

---

data/markdown/pages/learn/accelerate/xm-cloud/implementation/sitecore-search.md

Further changes to search throttle limit.

---

src/pages/changelog/[product]/[...entry].tsx

This PR adds support for PDFs in changelog entries
Local
- [ X New feature (non-breaking change which adds functionality)

Add support for pdf attachments

---

data/markdown/pages/learn/accelerate/content-hub/implementation/configuration/environment-specific-settings.md
data/markdown/pages/learn/accelerate/content-hub/implementation/custom-logic/external-integrations.md
data/markdown/pages/learn/accelerate/content-hub/index.md
data/markdown/pages/learn/accelerate/content-hub/pre-development/discovery/index.md
data/markdown/pages/learn/accelerate/content-hub/pre-development/discovery/requirements-gathering.md
data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/troubleshooting-docker.md
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/discovery/moving-to-saas.md
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/information-architecture/content-audit.md
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-architecture/site-management.md

2025-01 - Accelerate Updates

---

README.md
data/markdown/pages/contribute/index.md
data/markdown/pages/learn/accelerate/content-hub/pre-development/discovery/project-planning.md
data/markdown/pages/learn/accelerate/content-hub/pre-development/discovery/requirements-gathering.md
data/markdown/pages/learn/accelerate/content-hub/pre-development/sprint-zero/multi-environments-deployment.md
data/markdown/pages/learn/accelerate/xm-cloud/implementation/information-architecture/workflow.md
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/project-architecture/multisite.md

Grammar fixes

---

src/components/changelog/ChangelogEntries.tsx
src/components/changelog/ChangelogItemMeta.tsx
src/components/lists/accelerate/AccelerateUpdates.tsx
src/components/navigation/NavBar.tsx
src/components/navigation/SearchButton.tsx
src/components/ui/socialShare/SocialShare.tsx
src/pages/changelog/index.tsx
src/pages/index.tsx

This PR adds improvements for the roadmap, changelog and top nav bar for mobile devices
Staging

Mobile improvements

---

data/markdown/pages/learn/accelerate/xm-cloud/implementation/information-architecture/workflow.md

Fix to content accidentally changed.

Updated recipe with correct content.

---

data/markdown/pages/downloads/Sitecore_Experience_Platform/102/Sitecore_Experience_Platform_102_Update1/Release_Notes.md

Add missing release note 590395 to SXP 10.2.1 release notes.
Requested by PSS, pertaining to an already released fix, related to a specific ticket requested by a customer.
Tested on localhost.

SXP 10.2.1 Release Notes - add missing note 590395

---

data/markdown/pages/downloads/Sitecore_Stream_for_Platform_DXP/index.md
data/markdown/pages/downloads/index.md
data/markdown/pages/downloads/manifest.json

Adds a new documentation page containing information on new Sitecore Stream for Platform DXP module, which can be installed on a Sitecore XP deployment.
Tested on local host. Reviewed with scrum team who owns the code.

New Sitecore Stream for Platform DXP module information page

---

data/markdown/pages/downloads/index.md
data/markdown/pages/downloads/manifest.json
data/markdown/pages/downloads/xm-cloud/index.md

Repositioned the links to the XM to XM Cloud Migration Tool and the xDB to CDP Migration Tool on this Downloads page, from the Composable DXP section to Developer Tools & Resources section. 
Why: To remove confusion of composable downloads on a predominantly Platform DXP downloads page. And to simplify the Platform DXP downloads page. The initial design intent was for this downloads page to contain all downloads related to composable products, but in practice over time the only tools here are these two migration tools from Platform DXP to composable products. All other composable downloads and dependencies are linked from their respective product pages or from Sitecore Portal. 
Tested on localhost. Tested link from XMC page to the migration tool, and other navigation scenarios.

Reposition launch of XM>XMC and XP>CDP migration tools

---

data/markdown/pages/downloads/Sitecore_CLI/6x/Sitecore_CLI_600/index.md
data/markdown/pages/downloads/Sitecore_CLI/6x/Sitecore_CLI_6023/index.md
data/markdown/pages/downloads/Sitecore_CLI/index.md

Added description to Sitecore CLI 6 download pages, to avoid support questions. 
Driven by github.com/Sitecore/developer-portal/issues/978

Sitecore CLI page description

---

data/markdown/pages/downloads/Sitecore_Stream_for_Platform_DXP/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Stream_for_Platform_DXP/index.md

Updated existing download page to document new minor v1.1.34 release.
Moved release notes to a separate, single release notes page, tabulated for all releases.

New Sitecore Stream for Platform DXP release 1.1.34

---

data/markdown/pages/downloads/Sitecore_Identity/5x/Sitecore_Identity_500/index.md
data/markdown/pages/downloads/Sitecore_Identity/5x/Sitecore_Identity_501/index.md
data/markdown/pages/downloads/Sitecore_Identity/5x/Sitecore_Identity_510/index.md
data/markdown/pages/downloads/Sitecore_Identity/5x/Sitecore_Identity_511/index.md
data/markdown/pages/downloads/Sitecore_Identity/6x/Sitecore_Identity_600/index.md
data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70325/index.md
data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70326/index.md
data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70327/index.md
data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70328/index.md
data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70330/index.md
data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_70331/index.md
data/markdown/pages/downloads/Sitecore_Identity/7x/Sitecore_Identity_7111/index.md
data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8016/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8016/index.md
data/markdown/pages/downloads/Sitecore_Identity/index.md

Updated publishing progress on main index page, for customers eagerly awaiting artifacts.
Added to release notes.
Marked older versions as deprecated, due to discontinued Microsoft support for older .NET versions.

IS 8 Release Progress Update

---

data/markdown/pages/downloads/Sitecore_CLI/6x/Sitecore_CLI_6023/Release_Notes.md

Just released the doc topic today.

Added link to documentation in Release_Notes.md

---

data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8016/index.md

Status update to Identity Server 8.0 main download page. Eagerly anticipated.

Identity Server 8.0 status update

---

data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/cms-error-monitoring.md
data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/creating-new-components.md
data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/troubleshooting-docker.md
data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/using-placeholders.md
data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/web-application-error-handling.md
data/markdown/pages/learn/accelerate/xm-cloud/manifest.json
data/markdown/pages/learn/accelerate/xm-cloud/optimization/data-fetching-optimization.md
data/markdown/pages/learn/accelerate/xm-cloud/optimization/performance-optimization.md
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-considerations/component-design-best-practices.md
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/developer-considerations/web-developer-experience.md
data/markdown/pages/learn/accelerate/xm-cloud/pre-development/sprint-zero/project-solution-setup.md

Content Fixes
- CMS Error Monitoring
- Creating new components
- Troubleshooting docker
- Using Placeholder
- Web Application Error Monitoring
- Data Fetching Optimization
- Optimizing Performance
- Component Design Best Practices
- Web Developer Experience
- Project Solution Setup

2025-March

---

data/markdown/pages/downloads/Sitecore_Experience_Platform/101/Sitecore_Experience_Platform_101_Update1/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Headless_Rendering/22x/Sitecore_Headless_Rendering_2200/Release_Notes.md

Minor fixes to previous SXP and Headless Rendering release notes. Reference work items:
PDXP-980
PDXP-1203

SXP Release Notes fixes

---

data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8016/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8016/index.md

Updated status of compatibility testing on Identity Server 8 download page.
Added a status note on the Release Notes page.
This completes the Identity Server release.
Tested on localhost.

IS8 - completed compat testing - completed release

---

data/markdown/pages/downloads/Sitecore_Commerce/100/Sitecore_Experience_Commerce_100/index.md
data/markdown/pages/downloads/Sitecore_Commerce/101/Sitecore_Experience_Commerce_101/index.md
data/markdown/pages/downloads/Sitecore_Commerce/102/Sitecore_Experience_Commerce_102/index.md
data/markdown/pages/downloads/Sitecore_Commerce/103/Sitecore_Experience_Commerce_103/index.md

Updated compatibility info on XC 10.0 thru 10.3 download pages. Made it more generic, to better align with the corresponding App Compat KB article.
Ref: PSS DocRequest PDXP-1790

XC compatibility tidy

---

data/markdown/pages/downloads/Sitecore_Connect_for_Content_Hub/5x/Sitecore_Connect_for_Content_Hub_520/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Connect_for_Content_Hub/5x/Sitecore_Connect_for_Content_Hub_520/index.md

Updated release notes of Sitecore Connect for Content Hub 5.2 in response to customer feedback.
Converted entry 588808 from a new feature to a breaking change, and added more description.
Tidied release notes
Removed an expired alert from the Sitecore Connect for Content Hub 5.2 download page.
Tested on localhost.

SCCH Module 5.2 - release notes update

---

data/markdown/pages/downloads/Sitecore_Publishing_Service/8x/Sitecore_Publishing_Service_803/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Publishing_Service/8x/Sitecore_Publishing_Service_803/index.md
data/markdown/pages/downloads/Sitecore_Publishing_Service_Module/10x/Sitecore_Publishing_Service_Module_1040/index.md

* Updated the link in the SPS Module 10.4 download page to the latest SPS Module 10.4 Container Deployment Guide, so that it aligns with the guide version just published with SPS 8.0.3
* Tidied descriptions of this guide
* Fixed an incorrect date in SPS 8.0 release notes
localhost

SPS8.0 - update guide link and refs, fix release note

---

data/markdown/pages/learn/accelerate/content-hub/implementation/custom-logic/external-integrations.md

Fix to remove duplicate paragraph in recipe text.
Markdown viewer.

Accelerate - Content Hub - external-integrations.md - remove duplicate paragraph.

---

data/promos/survey.ts
src/pages/index.tsx

add PromoCard component to homepage and import survey data

---

data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8028/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8028/index.md
data/markdown/pages/downloads/Sitecore_Identity/index.md

Release of Identity Server Patch version 8.0.28
Tested on localhost in developer environment.

Identity Server 8.0.28 (Patch Release)

---

data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8028/Release_Notes.md
data/markdown/pages/downloads/Sitecore_Identity/8x/Sitecore_Identity_Server_8028/index.md
data/markdown/pages/downloads/Sitecore_Stream_for_Platform_DXP/index.md

Fixed broken link from IS 8.0.28 download page to corresponding ARM templates release in GitHub
Updated related descriptions on download page
Also included one minor tidy to the Stream download page 

IdentityServer8.0.28 - fix broken link to ARM templates
